exports.up = (knex) => knex.schema.withSchema('main').alterTable('users', (table) => {
    table.decimal('settingsTherrCoinTotal').defaultTo(0);
    table.decimal('settingsAreaCoinTotal').defaultTo(0);
    table.string('settingsBio', 255).defaultTo('');
    table.timestamp('settingsBirthdate', { useTz: true });
    table.string('settingsGender').defaultTo('');
    table.decimal('settingsLocale').defaultTo(0);
    table.string('settingsThemeName').defaultTo('light');
    table.string('settingsWebsite', 255).defaultTo('');
    table.jsonb('settingsPushTopics').defaultTo(JSON.stringify(['*']));
    table.boolean('settingsEmailMarketing').defaultTo(true);
    table.boolean('settingsEmailBackground').defaultTo(true);
    table.boolean('settingsEmailInvites').defaultTo(true);
    table.boolean('settingsEmailLikes').defaultTo(true);
    table.boolean('settingsEmailMentions').defaultTo(true);
    table.boolean('settingsEmailMessages').defaultTo(true);
    table.boolean('settingsEmailReminders').defaultTo(true);
    table.boolean('settingsPushMarketing').defaultTo(true);
    table.boolean('settingsPushBackground').defaultTo(true);
    table.boolean('settingsPushInvites').defaultTo(true);
    table.boolean('settingsPushLikes').defaultTo(true);
    table.boolean('settingsPushMentions').defaultTo(true);
    table.boolean('settingsPushMessages').defaultTo(true);
    table.boolean('settingsPushReminders').defaultTo(true);
});

exports.down = (knex) => knex.schema.withSchema('main').alterTable('users', (table) => {
    table.dropColumn('settingsTherrCoinTotal');
    table.dropColumn('settingsAreaCoinTotal');
    table.dropColumn('settingsBio');
    table.dropColumn('settingsBirthdate');
    table.dropColumn('settingsGender');
    table.dropColumn('settingsLocale');
    table.dropColumn('settingsThemeName');
    table.dropColumn('settingsWebsite');
    table.dropColumn('settingsPushTopics');
    table.dropColumn('settingsEmailMarketing');
    table.dropColumn('settingsEmailBackground');
    table.dropColumn('settingsEmailInvites');
    table.dropColumn('settingsEmailLikes');
    table.dropColumn('settingsEmailMentions');
    table.dropColumn('settingsEmailMessages');
    table.dropColumn('settingsEmailReminders');
    table.dropColumn('settingsPushMarketing');
    table.dropColumn('settingsPushBackground');
    table.dropColumn('settingsPushInvites');
    table.dropColumn('settingsPushLikes');
    table.dropColumn('settingsPushMentions');
    table.dropColumn('settingsPushMessages');
    table.dropColumn('settingsPushReminders');
});
