enum FeatureFlags {
    // Navigation Tabs
    ENABLE_AREAS = 'ENABLE_AREAS',
    ENABLE_GROUPS = 'ENABLE_GROUPS',
    ENABLE_MAP = 'ENABLE_MAP',
    ENABLE_CONNECT = 'ENABLE_CONNECT',

    // Content Types
    ENABLE_MOMENTS = 'ENABLE_MOMENTS',
    ENABLE_SPACES = 'ENABLE_SPACES',
    ENABLE_EVENTS = 'ENABLE_EVENTS',
    ENABLE_THOUGHTS = 'ENABLE_THOUGHTS',

    // Social Features
    ENABLE_DIRECT_MESSAGING = 'ENABLE_DIRECT_MESSAGING',
    ENABLE_ACHIEVEMENTS = 'ENABLE_ACHIEVEMENTS',
    ENABLE_ACTIVITIES = 'ENABLE_ACTIVITIES',
    ENABLE_NOTIFICATIONS = 'ENABLE_NOTIFICATIONS',

    // Groups Features
    ENABLE_FORUMS = 'ENABLE_FORUMS',
    ENABLE_ACTIVITY_SCHEDULER = 'ENABLE_ACTIVITY_SCHEDULER',

    // HABITS App Features
    ENABLE_HABITS = 'ENABLE_HABITS',
    ENABLE_PACTS = 'ENABLE_PACTS',
}

export {
    FeatureFlags,
};
