enum SocketServerActionTypes {
    // Socket
    CONNECT = 'SERVER:CONNECT',
    DISCONNECT = 'SERVER:DISCONNECT',

    // Sessions
    SESSION_CREATED = 'SERVER:SESSION_CREATED',
    SESSION_UPDATED = 'SERVER:SESSION_UPDATED',
    SESSION_CLOSED = 'SERVER:SESSION_CLOSED',

    // Auth
    USER_LOGIN_SUCCESS = 'SERVER:USER_LOGIN_SUCCESS',
    USER_LOGOUT_SUCCESS = 'SERVER:USER_LOGOUT_SUCCESS',
    UNAUTHORIZED = 'UNAUTHORIZED',

    // Connections
    ACTIVE_CONNECTIONS_LOADED = 'SERVER:ACTIVE_CONNECTIONS_LOADED',
    ACTIVE_CONNECTIONS_ADDED = 'SERVER:ACTIVE_CONNECTIONS_ADDED',
    ACTIVE_CONNECTION_LOGGED_IN = 'SERVER:ACTIVE_CONNECTION_LOGGED_IN',
    ACTIVE_CONNECTION_LOGGED_OUT = 'SERVER:ACTIVE_CONNECTION_LOGGED_OUT',
    ACTIVE_CONNECTION_DISCONNECTED = 'SERVER:ACTIVE_CONNECTION_DISCONNECTED',
    ACTIVE_CONNECTION_REFRESHED = 'SERVER:ACTIVE_CONNECTION_REFRESHED',
    USER_CONNECTION_CREATED = 'SERVER:USER_CONNECTION_CREATED',
    USER_CONNECTION_UPDATED = 'SERVER:USER_CONNECTION_UPDATED',

    // Notifications
    NOTIFICATION_CREATED = 'SERVER:NOTIFICATION_CREATED',
    NOTIFICATION_UPDATED = 'SERVER:NOTIFICATION_UPDATED',

    // Rooms
    JOINED_ROOM = 'SERVER:JOINED_ROOM',
    LEFT_ROOM = 'SERVER:LEFT_ROOM',
    OTHER_JOINED_ROOM = 'SERVER:OTHER_JOINED_ROOM',
    SEND_ROOMS_LIST = 'SERVER:SEND_ROOMS_LIST',

    // Messages
    SEND_DIRECT_MESSAGE = 'SERVER:SEND_DIRECT_MESSAGE',
    SEND_MESSAGE = 'SERVER:SEND_MESSAGE',

    // User
    UPDATE_USER = 'SERVER:UPDATE_USER',

    // HABITS: Pacts
    JOINED_PACT = 'SERVER:JOINED_PACT',
    LEFT_PACT = 'SERVER:LEFT_PACT',
    PARTNER_JOINED_PACT = 'SERVER:PARTNER_JOINED_PACT',
    PARTNER_LEFT_PACT = 'SERVER:PARTNER_LEFT_PACT',
    CHECKIN_LOGGED = 'SERVER:CHECKIN_LOGGED',
    PARTNER_CHECKED_IN = 'SERVER:PARTNER_CHECKED_IN',
    CELEBRATION_RECEIVED = 'SERVER:CELEBRATION_RECEIVED',
    ENCOURAGEMENT_RECEIVED = 'SERVER:ENCOURAGEMENT_RECEIVED',
    STREAK_MILESTONE = 'SERVER:STREAK_MILESTONE',
    PACT_ACTIVITY = 'SERVER:PACT_ACTIVITY',
}

export default SocketServerActionTypes;
