extends: 'stylelint-config-standard-scss'
rules:
  no-descending-specificity: null
  scss/function-no-unknown: null
  scss/at-rule-no-unknown: null
  no-invalid-position-at-import-rule: null
  import-notation: null
  scss/operator-no-newline-after: null
  declaration-property-value-no-unknown: null
  annotation-no-unknown:
    - true
    - ignoreAnnotations:
        - default
        - global
  media-feature-range-notation: null
  scss/dollar-variable-pattern: null
  at-rule-empty-line-before: null
  scss/no-global-function-names: null
  scss/double-slash-comment-empty-line-before: null
