language: node_js
install:
  - npm run install:all:ci
script:
  - npm run build:all
  - npm run test:all
after_success:
  - git commit -a -m "Committed by Travis-CI build number, $((TRAVIS_JOB_ID - 1))" --no-verify
  - git push origin HEAD