sudo: required
services:
  - docker
language: node_js
# before_install:
#   - _bin/travis/before-install.sh
install:
  - _bin/travis/install.sh
cache: npm
jobs:
  include:
    - stage: "Build and test"
      name: "Build and test app services"
      script: _bin/travis/build.sh && _bin/travis/test.sh
after_success:
  - _bin/travis/after-success.sh
# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: "rili-app"
#   env: "RiliApp-env"
#   bucket_name: "elasticbeanstalk-us-east-2-014278409774"
#   bucket_path: "rili-app"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY