language: node_js
jobs:
  include:
    - stage: "Pre-Check"
      name: "Check if running the full build is necessary"
      script: _bin/travis/pre-check.sh
    - stage: "Install"
      name: "Install app dependencies"
      script: _bin/travis/install.sh
    - stage: "Build"
      name: "Build app services"
      script: _bin/travis/build.sh
    - stage: "Test"
      name: "Test app services"
      script: _bin/travis/test.sh
after_success:
  - _bin/travis/post-build.sh