language: node_js
install: true
cache: npm
jobs:
  include:
    - stage: "Install"
      name: "Install app dependencies"
      script: _bin/travis/install.sh
    - stage: "Build"
      name: "Build app services"
      script: _bin/travis/build.sh
    - stage: "Test"
      name: "Test app services"
      script: _bin/travis/test.sh
    - stage: "Deploy"
      name: "Commit and push build changes"
      script: _bin/travis/post-build.sh
      if: branch = master