language: node_js
install: _bin/travis/install.sh
cache: npm
jobs:
  include:
    - stage: "Build and test"
      name: "Build and test app services"
      script: _bin/travis/build.sh && _bin/travis/test.sh
after_success:
  - _bin/travis/post-build.sh