sudo: required
services:
  - docker
language: node_js
cache: npm
env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - _bin/travis/before-install.sh
# install:
#   - _bin/travis/install.sh
# jobs:
#   include:
#     - stage: "Build and test"
#       name: "Build and test app services"
#       script: docker run -e CI=true riliadmin/testing npm run test
# after_success:
#   - _bin/travis/after-success.sh
deploy:
  provider: script
  script: bash _bin/travis/deploy.sh
  on:
    branch: master