sudo: required
services:
  - docker
language: node_js
# before_install:
#   - _bin/travis/before-install.sh
install:
  - _bin/travis/install.sh
cache: npm
jobs:
  include:
    - stage: "Build and test"
      name: "Build and test app services"
      script: _bin/travis/build.sh && _bin/travis/test.sh
after_success:
  - _bin/travis/after-success.sh