language: node_js
install: _bin/travis/install.sh
cache: npm
jobs:
  include:
    - stage: "Build"
      name: "Build app services"
      script: _bin/travis/build.sh
    - stage: "Test"
      name: "Test app services"
      script: _bin/travis/test.sh
    - stage: "Deploy"
      name: "Commit and push build changes"
      script: _bin/travis/post-build.sh
      if: branch = master