apiVersion: skaffold/v2alpha3
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: riliadmin/client-web
      context: .
      docker:
        dockerfile: ./rili-client-web/Dockerfile
      sync:
        infer:
          - './rili-client-web/**/*.js'
          - './rili-client-web/**/*.json'
          - './rili-client-web/**/*.css'
          - './rili-client-web/**/*.html'
          - './rili-client-web/**/*.hbs'
          - './rili-public-library/**/lib/*.js'
          - './rili-public-library/**/lib/*.json'
          - './rili-public-library/**/lib/*.css'
          - './rili-public-library/**/lib/*.html'
    - image: riliadmin/server-api
      context: .
      docker:
        dockerfile: ./rili-server/Dockerfile.api
      sync:
        infer:
          - './rili-server/**/*.js'
          - './rili-public-library/utilities/**/lib/*.js'
          - './rili-public-library/utilities/**/lib/*.json'
    - image: riliadmin/server-socket
      context: .
      docker:
        dockerfile: ./rili-server/Dockerfile.socket
      sync:
        infer:
          - './rili-server/**/*.js'
          - './rili-public-library/utilities/**/lib/*.js'
          - './rili-public-library/utilities/**/lib/*.json'
deploy:
  kubectl:
    manifests:
      - k8s/client-cluster-ip-service.yaml
      - k8s/client-deployment.yaml
      - k8s/server-api-cluster-ip-service.yaml
      - k8s/server-api-deployment.yaml
      - k8s/server-socket-cluster-ip-service.yaml
      - k8s/server-socket-deployment.yaml
      - k8s/redis-cluster-ip-service.yaml
      - k8s/redis-deployment.yaml