apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: riliadmin/client-web
      context: .
      docker:
        dockerfile: ./rili-client-web/Dockerfile
      sync:
        './rili-client-web/**/*.js': ./rili-client-web
        './rili-client-web/**/*.json': ./rili-client-web
        './rili-client-web/**/*.css': ./rili-client-web
        './rili-client-web/**/*.html': ./rili-client-web
        './rili-client-web/**/*.hbs': ./rili-client-web
        './rili-public-library/**/lib/*.js': ./rili-public-library
        './rili-public-library/**/lib/*.json': ./rili-public-library
        './rili-public-library/**/lib/*.css': ./rili-public-library
        './rili-public-library/**/lib/*.html': ./rili-public-library
    - image: riliadmin/server-api
      context: .
      docker:
        dockerfile: ./rili-server/Dockerfile.api
      sync:
        './rili-server/**/*.js': ./rili-server
        './rili-public-library/utilities/**/lib/*.js': ./rili-public-library/utilities
        './rili-public-library/utilities/**/lib/*.json': ./rili-public-library/utilities
    - image: riliadmin/server-socket
      context: .
      docker:
        dockerfile: ./rili-server/Dockerfile.socket
      sync:
        './rili-server/**/*.js': .
        './rili-public-library/utilities/**/lib/*.js': ./rili-public-library/utilities
        './rili-public-library/utilities/**/lib/*.json': ./rili-public-library/utilities
deploy:
  kubectl:
    manifests:
      - k8s/client-cluster-ip-service.yaml
      - k8s/client-deployment.yaml
      - k8s/server-api-cluster-ip-service.yaml
      - k8s/server-api-deployment.yaml
      - k8s/server-socket-cluster-ip-service.yaml
      - k8s/server-socket-deployment.yaml
      - k8s/redis-cluster-ip-service.yaml
      - k8s/redis-deployment.yaml