apiVersion: skaffold/v2alpha3
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: therrapp/client-web
      context: .
      docker:
        dockerfile: ./rili-client-web/Dockerfile
      sync:
        infer:
          - './rili-client-web/**/*.js'
          - './rili-client-web/**/*.json'
          - './rili-client-web/**/*.css'
          - './rili-client-web/**/*.html'
          - './rili-client-web/**/*.hbs'
          - './rili-public-library/**/lib/*.js'
          - './rili-public-library/**/lib/*.json'
          - './rili-public-library/**/lib/*.css'
          - './rili-public-library/**/lib/*.html'
    - image: therrapp/users-service
      context: .
      docker:
        dockerfile: ./rili-servers/users-service/Dockerfile
      sync:
        infer:
          - './rili-servers/users-service/**/*.js'
          - './rili-public-library/rili-js-utilities/**/lib/*.js'
          - './rili-public-library/rili-js-utilities/**/lib/*.json'
    - image: therrapp/websocket-service
      context: .
      docker:
        dockerfile: ./rili-servers/websocket-service/Dockerfile
      sync:
        infer:
          - './rili-servers/websocket-service/**/*.js'
          - './rili-public-library/rili-js-utilities/**/lib/*.js'
          - './rili-public-library/rili-js-utilities/**/lib/*.json'
deploy:
  kubectl:
    manifests:
      - k8s/client-cluster-ip-service.yaml
      - k8s/client-deployment.yaml
      - k8s/users-service-cluster-ip-service.yaml
      - k8s/users-service-deployment.yaml
      - k8s/websocket-service-cluster-ip-service.yaml
      - k8s/websocket-service-deployment.yaml
      - k8s/redis-cluster-ip-service.yaml
      - k8s/redis-deployment.yaml