enum SocketServerActionTypes {
    // Socket
    DISCONNECT = 'SERVER:DISCONNECT',

    // Sessions
    SESSION_CREATED_MESSAGE = 'SERVER:SESSION_CREATED_MESSAGE',
    SESSION_CLOSED_MESSAGE = 'SERVER:SESSION_CLOSED_MESSAGE',

    // Auth
    USER_LOGIN_SUCCESS = 'SERVER:USER_LOGIN_SUCCESS',
    USER_LOGOUT_SUCCESS = 'SERVER:USER_LOGOUT_SUCCESS',

    // Connections
    CONNECTION_UPDATED = 'SERVER:CONNECTION_UPDATED',

    // Notifications
    NOTIFICATION_UPDATED = 'SERVER:NOTIFICATION_UPDATED',

    // Rooms
    JOINED_ROOM = 'SERVER:JOINED_ROOM',
    LEFT_ROOM = 'SERVER:LEFT_ROOM',
    OTHER_JOINED_ROOM = 'SERVER:OTHER_JOINED_ROOM',
    SEND_ROOMS_LIST = 'SERVER:SEND_ROOMS_LIST',

    // Messages
    SEND_MESSAGE = 'SERVER:SEND_MESSAGE',
}

export default SocketServerActionTypes;
