enum SocketClientActionTypes {
    // AUTHENTICATION
    LOGIN = 'CLIENT:LOGIN',
    LOGOUT = 'CLIENT:LOGOUT',
    REGISTER = 'CLIENT:REGISTER',

    // ROOMS
    JOIN_ROOM = 'CLIENT:JOIN_ROOM',

    // MESSAGES
    SEND_MESSAGE = 'CLIENT:SEND_MESSAGE',

    // NOTIFICATIONS
    UPDATE_NOTIFICATION = 'CLIENT:UPDATE_NOTIFICATION',

    // USER CONNECTIONS
    UPDATE_USER_CONNECTION = 'CLIENT:UPDATE_USER_CONNECTION'
}

export default SocketClientActionTypes;
