enum SocketClientActionTypes {
    JOIN_ROOM = 'CLIENT:JOIN_ROOM',
    LOGIN = 'CLIENT:LOGIN',
    LOGOUT = 'CLIENT:LOGOUT',
    REGISTER = 'CLIENT:REGISTER',
    SEND_MESSAGE = 'CLIENT:SEND_MESSAGE',
    UPDATE_NOTIFICATION = 'CLIENT:UPDATE_NOTIFICATION',
}

export default SocketClientActionTypes;
