enum SocketServerActionTypes {
    // Socket
    CONNECT = 'SERVER:CONNECT',
    DISCONNECT = 'SERVER:DISCONNECT',

    // Sessions
    SESSION_CREATED = 'SERVER:SESSION_CREATED',
    SESSION_UPDATED = 'SERVER:SESSION_UPDATED',
    SESSION_CLOSED = 'SERVER:SESSION_CLOSED',

    // Auth
    USER_LOGIN_SUCCESS = 'SERVER:USER_LOGIN_SUCCESS',
    USER_LOGOUT_SUCCESS = 'SERVER:USER_LOGOUT_SUCCESS',
    UNAUTHORIZED = 'UNAUTHORIZED',

    // Connections
    USER_CONNECTION_CREATED = 'SERVER:USER_CONNECTION_CREATED',
    USER_CONNECTION_UPDATED = 'SERVER:USER_CONNECTION_UPDATED',

    // Notifications
    NOTIFICATION_CREATED = 'SERVER:NOTIFICATION_CREATED',
    NOTIFICATION_UPDATED = 'SERVER:NOTIFICATION_UPDATED',

    // Rooms
    JOINED_ROOM = 'SERVER:JOINED_ROOM',
    LEFT_ROOM = 'SERVER:LEFT_ROOM',
    OTHER_JOINED_ROOM = 'SERVER:OTHER_JOINED_ROOM',
    SEND_ROOMS_LIST = 'SERVER:SEND_ROOMS_LIST',

    // Messages
    SEND_MESSAGE = 'SERVER:SEND_MESSAGE',
}

export default SocketServerActionTypes;
