/**
 * Seed file for the interests table
 * Run with: npm run seeds:run (from users-service directory)
 *
 * Uses ON CONFLICT DO NOTHING to gracefully handle existing data in all environments.
 * If the data already exists, it will be skipped without error.
 */

const interests = [
    {
        id: '05f56a5a-dd56-43df-bc43-fd706f571881',
        tag: 'gymWorkouts',
        categoryKey: 'interestsCategories.sports',
        displayNameKey: 'interests.sports.gymWorkouts',
        emoji: '🏋️',
        iconGroup: 'font-awesome-5',
        iconId: 'futbol',
        iconColor: '#000000',
    },
    {
        id: '0ad98db7-4817-4304-a73b-319cc415894f',
        tag: 'coffee',
        categoryKey: 'interestsCategories.foodDrink',
        displayNameKey: 'interests.foodDrink.coffee',
        emoji: '☕',
        iconGroup: 'font-awesome-5',
        iconId: 'drink',
        iconColor: '#000000',
    },
    {
        id: '0e02deb0-e1b2-459e-aa93-5946e06b356e',
        tag: 'socer',
        categoryKey: 'interestsCategories.sports',
        displayNameKey: 'interests.sports.soccer',
        emoji: '⚽',
        iconGroup: 'font-awesome-5',
        iconId: 'futbol',
        iconColor: '#f9ad2a',
    },
    {
        id: '1120476c-2bc7-4df1-bf43-a068a56a5918',
        tag: 'videoGamesConsole',
        categoryKey: 'interestsCategories.games',
        displayNameKey: 'interests.games.videoGamesConsole',
        emoji: '🎮',
        iconGroup: 'font-awesome-5',
        iconId: 'futbol',
        iconColor: '#000000',
    },
    {
        id: '12ef39e6-26e4-4570-a35d-42d429b474e8',
        tag: 'skinCare',
        categoryKey: 'interestsCategories.fashion',
        displayNameKey: 'interests.fashion.skinCare',
        emoji: '🧴',
        iconGroup: 'font-awesome-5',
        iconId: 'art',
        iconColor: '#000000',
    },
    {
        id: '134f5e29-c740-4eaa-ac99-fc73d747aa29',
        tag: 'science',
        categoryKey: 'interestsCategories.scienceTech',
        displayNameKey: 'interests.scienceTech.science',
        emoji: '🔬',
        iconGroup: 'font-awesome-5',
        iconId: 'science',
        iconColor: '#000000',
    },
    {
        id: '13e61623-a08e-4713-9245-3945fba3c4eb',
        tag: 'software',
        categoryKey: 'interestsCategories.scienceTech',
        displayNameKey: 'interests.scienceTech.software',
        emoji: '⌨️',
        iconGroup: 'font-awesome-5',
        iconId: 'science',
        iconColor: '#000000',
    },
    {
        id: '14e2bff0-e9c3-4ab8-8ce1-6f6f4c04fb14',
        tag: 'bodyArtCostume',
        categoryKey: 'interestsCategories.fashion',
        displayNameKey: 'interests.fashion.bodyArtCostume',
        emoji: '🎭',
        iconGroup: 'font-awesome-5',
        iconId: 'art',
        iconColor: '#000000',
    },
    {
        id: '1a5586f8-4d31-4be6-a3cb-efc4c35b2d63',
        tag: 'veganFood',
        categoryKey: 'interestsCategories.foodDrink',
        displayNameKey: 'interests.foodDrink.veganFood',
        emoji: '🥗',
        iconGroup: 'font-awesome-5',
        iconId: 'drink',
        iconColor: '#000000',
    },
    {
        id: '1cde3ad1-5716-49dd-a179-882f322a3274',
        tag: 'baseball',
        categoryKey: 'interestsCategories.sports',
        displayNameKey: 'interests.sports.baseball',
        emoji: '⚾',
        iconGroup: 'font-awesome-5',
        iconId: 'futbol',
        iconColor: '#f9ad2a',
    },
    {
        id: '1d4b223d-72c2-4d16-a776-a2677703d28f',
        tag: 'gymnastics',
        categoryKey: 'interestsCategories.sports',
        displayNameKey: 'interests.sports.gymnastics',
        emoji: '🤸',
        iconGroup: 'font-awesome-5',
        iconId: 'futbol',
        iconColor: '#f9ad2a',
    },
    {
        id: '20384ca0-a6b0-4cc3-919d-06e89253d17d',
        tag: 'textileArt',
        categoryKey: 'interestsCategories.arts',
        displayNameKey: 'interests.arts.textileArt',
        emoji: '🧺',
        iconGroup: 'font-awesome-5',
        iconId: 'art',
        iconColor: '#000000',
    },
    {
        id: '25c8fc03-4e66-4d43-996f-7d5bd36d4bb8',
        tag: 'happyHour',
        categoryKey: 'interestsCategories.foodDrink',
        displayNameKey: 'interests.foodDrink.happyHour',
        emoji: '🍹',
        iconGroup: 'font-awesome-5',
        iconId: 'drink',
        iconColor: '#000000',
    },
    {
        id: '2b6df2e7-c202-48fe-a865-54a31b65596c',
        tag: 'drawing',
        categoryKey: 'interestsCategories.arts',
        displayNameKey: 'interests.arts.drawing',
        emoji: '✏️',
        iconGroup: 'font-awesome-5',
        iconId: 'art',
        iconColor: '#000000',
    },
    {
        id: '2e4e8128-5dc0-4bdd-8919-5ad932104148',
        tag: 'hardware',
        categoryKey: 'interestsCategories.scienceTech',
        displayNameKey: 'interests.scienceTech.hardware',
        emoji: '⚙️',
        iconGroup: 'font-awesome-5',
        iconId: 'science',
        iconColor: '#000000',
    },
    {
        id: '33d49eb4-a786-4939-99fa-d29f7c5269fb',
        tag: 'liveMusic',
        categoryKey: 'interestsCategories.arts',
        displayNameKey: 'interests.arts.liveMusic',
        emoji: '🎸',
        iconGroup: 'font-awesome-5',
        iconId: 'futbol',
        iconColor: '#000000',
    },
    {
        id: '34c1b293-0928-4967-b6b9-44fb4c36ebf1',
        tag: 'travel',
        categoryKey: 'interestsCategories.travelTransport',
        displayNameKey: 'interests.travelTransport.travel',
        emoji: '🛫',
        iconGroup: 'font-awesome-5',
        iconId: 'business',
        iconColor: '#000000',
    },
    {
        id: '358e3197-1be5-4bd7-8eae-3fce85d778c6',
        tag: 'businessTravel',
        categoryKey: 'interestsCategories.business',
        displayNameKey: 'interests.business.businessTravel',
        emoji: '💼',
        iconGroup: 'font-awesome-5',
        iconId: 'business',
        iconColor: '#000000',
    },
    {
        id: '3b799d2b-4fef-4cff-b6b7-19a901c0bad1',
        tag: 'makeup',
        categoryKey: 'interestsCategories.fashion',
        displayNameKey: 'interests.fashion.makeup',
        emoji: '💄',
        iconGroup: 'font-awesome-5',
        iconId: 'art',
        iconColor: '#000000',
    },
    {
        id: '4234d4eb-2373-4e89-a551-1b85fc8a08e9',
        tag: 'financialMarkets',
        categoryKey: 'interestsCategories.business',
        displayNameKey: 'interests.business.financialMarkets',
        emoji: '📈',
        iconGroup: 'font-awesome-5',
        iconId: 'business',
        iconColor: '#000000',
    },
    {
        id: '4270c685-0d88-4aec-9df8-470d7fc1398e',
        tag: 'languageSkills',
        categoryKey: 'interestsCategories.business',
        displayNameKey: 'interests.business.languageSkills',
        emoji: '🤟',
        iconGroup: 'font-awesome-5',
        iconId: 'business',
        iconColor: '#000000',
    },
    {
        id: '468c1bee-0644-4862-a135-42610a1f79e8',
        tag: 'tennis',
        categoryKey: 'interestsCategories.sports',
        displayNameKey: 'interests.sports.tennis',
        emoji: '🎾',
        iconGroup: 'font-awesome-5',
        iconId: 'futbol',
        iconColor: '#000000',
    },
    {
        id: '49c0899d-4033-4fb1-8604-ff1883f5400f',
        tag: 'photography',
        categoryKey: 'interestsCategories.arts',
        displayNameKey: 'interests.arts.photography',
        emoji: '📷',
        iconGroup: 'font-awesome-5',
        iconId: 'art',
        iconColor: '#000000',
    },
    {
        id: '4a9d27fb-19a4-4127-956a-3f8e1a9c950b',
        tag: 'swimWear',
        categoryKey: 'interestsCategories.fashion',
        displayNameKey: 'interests.fashion.swimWear',
        emoji: '👙',
        iconGroup: 'font-awesome-5',
        iconId: 'art',
        iconColor: '#000000',
    },
    {
        id: '518e79c1-5e8b-45a7-8cea-012d66c17908',
        tag: 'restaurant',
        categoryKey: 'interestsCategories.business',
        displayNameKey: 'interests.business.restaurant',
        emoji: '🍽️',
        iconGroup: 'font-awesome-5',
        iconId: 'business',
        iconColor: '#000000',
    },
    {
        id: '5a66a4be-b5b7-496b-b6b9-34497defbcc5',
        tag: 'anime',
        categoryKey: 'interestsCategories.arts',
        displayNameKey: 'interests.arts.anime',
        emoji: '🎭',
        iconGroup: 'font-awesome-5',
        iconId: 'art',
        iconColor: '#000000',
    },
    {
        id: '5bab589b-73e6-4351-876d-7c2b61e35605',
        tag: 'crafts',
        categoryKey: 'interestsCategories.arts',
        displayNameKey: 'interests.arts.crafts',
        emoji: '🧶',
        iconGroup: 'font-awesome-5',
        iconId: 'art',
        iconColor: '#000000',
    },
    {
        id: '5f785d1f-bf5c-49fb-a7f0-6dc7dd02796c',
        tag: 'teaching',
        categoryKey: 'interestsCategories.business',
        displayNameKey: 'interests.business.teaching',
        emoji: '📚',
        iconGroup: 'font-awesome-5',
        iconId: 'business',
        iconColor: '#000000',
    },
    {
        id: '629ca3e0-6074-4fe9-9b5a-62860cb4c1b5',
        tag: 'comedy',
        categoryKey: 'interestsCategories.arts',
        displayNameKey: 'interests.arts.comedy',
        emoji: '🎭',
        iconGroup: 'font-awesome-5',
        iconId: 'art',
        iconColor: '#000000',
    },
    {
        id: '662da7ce-ecc6-4452-a6bc-8844388bafe7',
        tag: 'running',
        categoryKey: 'interestsCategories.sports',
        displayNameKey: 'interests.sports.running',
        emoji: '🏃‍♀️',
        iconGroup: 'font-awesome-5',
        iconId: 'futbol',
        iconColor: '#000000',
    },
    {
        id: '6a088f5c-6324-46f2-9742-26279427ceb6',
        tag: 'tableTopGames',
        categoryKey: 'interestsCategories.games',
        displayNameKey: 'interests.games.tableTopGames',
        emoji: '🏓',
        iconGroup: 'font-awesome-5',
        iconId: 'futbol',
        iconColor: '#000000',
    },
    {
        id: '7e22760b-f69c-48b4-bc98-2877e534dadf',
        tag: 'localBusiness',
        categoryKey: 'interestsCategories.business',
        displayNameKey: 'interests.business.localBusiness',
        emoji: '📍',
        iconGroup: 'font-awesome-5',
        iconId: 'business',
        iconColor: '#000000',
    },
    {
        id: '86cdd824-4363-4093-a8cb-22699262010b',
        tag: 'careerDevelopment',
        categoryKey: 'interestsCategories.business',
        displayNameKey: 'interests.business.careerDevelopment',
        emoji: '👔',
        iconGroup: 'font-awesome-5',
        iconId: 'business',
        iconColor: '#000000',
    },
    {
        id: '88e32ae2-b192-402d-b2f4-32b400825828',
        tag: 'footwear',
        categoryKey: 'interestsCategories.fashion',
        displayNameKey: 'interests.fashion.footwear',
        emoji: '👟',
        iconGroup: 'font-awesome-5',
        iconId: 'art',
        iconColor: '#000000',
    },
    {
        id: '8b2c7418-935a-4dcd-9b28-ef1aa93df835',
        tag: 'billiards',
        categoryKey: 'interestsCategories.sports',
        displayNameKey: 'interests.sports.billiards',
        emoji: '🎱',
        iconGroup: 'font-awesome-5',
        iconId: 'futbol',
        iconColor: '#000000',
    },
    {
        id: '95cd2edf-bcdd-42a4-8eef-683b71f11b4c',
        tag: 'activeWear',
        categoryKey: 'interestsCategories.fashion',
        displayNameKey: 'interests.fashion.activeWear',
        emoji: '🏃',
        iconGroup: 'font-awesome-5',
        iconId: 'art',
        iconColor: '#000000',
    },
    {
        id: '95f2d44e-5d12-45c6-8bc1-c7eb4f63f54a',
        tag: 'reading',
        categoryKey: 'interestsCategories.arts',
        displayNameKey: 'interests.arts.reading',
        emoji: '📚',
        iconGroup: 'font-awesome-5',
        iconId: 'art',
        iconColor: '#000000',
    },
    {
        id: '97e59e4f-76f2-4ea9-b377-d06dd782ab73',
        tag: 'cars',
        categoryKey: 'interestsCategories.travelTransport',
        displayNameKey: 'interests.travelTransport.cars',
        emoji: '🏎️',
        iconGroup: 'font-awesome-5',
        iconId: 'futbol',
        iconColor: '#000000',
    },
    {
        id: '97f8ce40-a7bc-449a-97a4-10d6dce0ee1e',
        tag: 'desserts',
        categoryKey: 'interestsCategories.foodDrink',
        displayNameKey: 'interests.foodDrink.desserts',
        emoji: '🍦',
        iconGroup: 'font-awesome-5',
        iconId: 'drink',
        iconColor: '#000000',
    },
    {
        id: '99ae76f9-64b8-4181-9b44-67ee72f3f307',
        tag: 'hockey',
        categoryKey: 'interestsCategories.sports',
        displayNameKey: 'interests.sports.hockey',
        emoji: '🏒',
        iconGroup: 'font-awesome-5font-awesome-5',
        iconId: 'futbol',
        iconColor: '#f9ad2a',
    },
    {
        id: '9bf4bec7-b488-48f6-94de-07cae5702ec1',
        tag: 'volleyball',
        categoryKey: 'interestsCategories.sports',
        displayNameKey: 'interests.sports.volleyball',
        emoji: '🏐',
        iconGroup: 'font-awesome-5',
        iconId: 'futbol',
        iconColor: '#000000',
    },
    {
        id: '9d29aaec-067a-4cef-9b6c-e8d1a8adeece',
        tag: 'singing',
        categoryKey: 'interestsCategories.arts',
        displayNameKey: 'interests.arts.singing',
        emoji: '🎤',
        iconGroup: 'font-awesome-5',
        iconId: 'art',
        iconColor: '#000000',
    },
    {
        id: 'a2724265-5419-43e2-9868-52ba9c0a5d76',
        tag: 'juiceSmoothies',
        categoryKey: 'interestsCategories.foodDrink',
        displayNameKey: 'interests.foodDrink.juiceSmoothies',
        emoji: '🥤',
        iconGroup: 'font-awesome-5',
        iconId: 'drink',
        iconColor: '#000000',
    },
    {
        id: 'ad8062e1-98cd-483d-80d2-1fb979612e1b',
        tag: 'visualArts',
        categoryKey: 'interestsCategories.arts',
        displayNameKey: 'interests.arts.visualArts',
        emoji: '🖼️',
        iconGroup: 'font-awesome-5',
        iconId: 'art',
        iconColor: '#000000',
    },
    {
        id: 'b24d3146-9529-4f3c-9ca8-21b054ee91e1',
        tag: 'styleTrends',
        categoryKey: 'interestsCategories.fashion',
        displayNameKey: 'interests.fashion.styleTrends',
        emoji: '📉',
        iconGroup: 'font-awesome-5',
        iconId: 'art',
        iconColor: '#000000',
    },
    {
        id: 'bee8a5e4-fcde-4245-8e6a-5b29b3a82055',
        tag: 'dining',
        categoryKey: 'interestsCategories.foodDrink',
        displayNameKey: 'interests.foodDrink.dining',
        emoji: '🍽️',
        iconGroup: 'font-awesome-5',
        iconId: 'drink',
        iconColor: '#000000',
    },
    {
        id: 'c4e4ce72-4b7a-4f4f-b007-82bf7c12827f',
        tag: 'golf',
        categoryKey: 'interestsCategories.sports',
        displayNameKey: 'interests.sports.golf',
        emoji: '🏌️',
        iconGroup: 'font-awesome-5',
        iconId: 'futbol',
        iconColor: '#000000',
    },
    {
        id: 'c4ffd81f-28e4-4995-8863-338d703e1581',
        tag: 'cycling',
        categoryKey: 'interestsCategories.sports',
        displayNameKey: 'interests.sports.cycling',
        emoji: '🚲',
        iconGroup: 'font-awesome-5',
        iconId: 'futbol',
        iconColor: '#000000',
    },
    {
        id: 'c70eda00-232c-42b7-bb57-dd123063565c',
        tag: 'ramen',
        categoryKey: 'interestsCategories.foodDrink',
        displayNameKey: 'interests.foodDrink.ramen',
        emoji: '🍲',
        iconGroup: 'font-awesome-5',
        iconId: 'drink',
        iconColor: '#000000',
    },
    {
        id: 'cf69f60e-c567-4ec5-ad4f-06c4d2417d88',
        tag: 'cocktails',
        categoryKey: 'interestsCategories.foodDrink',
        displayNameKey: 'interests.foodDrink.cocktails',
        emoji: '🥤',
        iconGroup: 'font-awesome-5',
        iconId: 'drink',
        iconColor: '#000000',
    },
    {
        id: 'd352ff01-b5a3-4f97-a441-f692115d0417',
        tag: 'hairCare',
        categoryKey: 'interestsCategories.fashion',
        displayNameKey: 'interests.fashion.hairCare',
        emoji: '🪮',
        iconGroup: 'font-awesome-5',
        iconId: 'art',
        iconColor: '#000000',
    },
    {
        id: 'd48219b5-41fe-4e58-b873-00466d024f91',
        tag: 'jobSearch',
        categoryKey: 'interestsCategories.business',
        displayNameKey: 'interests.business.jobSearch',
        emoji: '👔',
        iconGroup: 'font-awesome-5',
        iconId: 'business',
        iconColor: '#000000',
    },
    {
        id: 'd639f49d-d902-49f2-ab88-2e99ceeb5c23',
        tag: 'bowling',
        categoryKey: 'interestsCategories.sports',
        displayNameKey: 'interests.sports.bowling',
        emoji: '🎳',
        iconGroup: 'font-awesome-5',
        iconId: 'futbol',
        iconColor: '#000000',
    },
    {
        id: 'd6abc4dd-c02e-4220-ad6c-308577c2c0ac',
        tag: 'football',
        categoryKey: 'interestsCategories.sports',
        displayNameKey: 'interests.sports.football',
        emoji: '🏈',
        iconGroup: 'font-awesome-5',
        iconId: 'futbol',
        iconColor: '#f9ad2a',
    },
    {
        id: 'd7aebc2a-ed15-4d80-9ad2-555fc6886805',
        tag: 'entrepreneurship',
        categoryKey: 'interestsCategories.business',
        displayNameKey: 'interests.business.entrepreneurship',
        emoji: '🕴🏾',
        iconGroup: 'font-awesome-5',
        iconId: 'business',
        iconColor: '#000000',
    },
    {
        id: 'd91d8fa9-24bb-4be9-a72b-3df78a638367',
        tag: 'collegeLife',
        categoryKey: 'interestsCategories.business',
        displayNameKey: 'interests.business.collegeLife',
        emoji: '🎓',
        iconGroup: 'font-awesome-5',
        iconId: 'business',
        iconColor: '#000000',
    },
    {
        id: 'dc8e3ce2-e36a-48c5-9bfb-f983399ff55e',
        tag: 'clothingAccessories',
        categoryKey: 'interestsCategories.fashion',
        displayNameKey: 'interests.fashion.clothingAccessories',
        emoji: '👗',
        iconGroup: 'font-awesome-5',
        iconId: 'art',
        iconColor: '#000000',
    },
    {
        id: 'dd3272bd-d65f-4515-a66e-7670287f80b5',
        tag: 'painting',
        categoryKey: 'interestsCategories.arts',
        displayNameKey: 'interests.arts.painting',
        emoji: '🎨',
        iconGroup: 'font-awesome-5',
        iconId: 'art',
        iconColor: '#f9ad2a',
    },
    {
        id: 'dd59eafe-eb6a-4b67-973b-4bf0cc3024ad',
        tag: 'digitalArt',
        categoryKey: 'interestsCategories.arts',
        displayNameKey: 'interests.arts.digitalArt',
        emoji: '🖥️',
        iconGroup: 'font-awesome-5',
        iconId: 'art',
        iconColor: '#000000',
    },
    {
        id: 'e0b16b99-a33f-4f09-8e28-ec8b47e9eb4e',
        tag: 'bbqGrilling',
        categoryKey: 'interestsCategories.foodDrink',
        displayNameKey: 'interests.foodDrink.bbqGrilling',
        emoji: '🔥',
        iconGroup: 'font-awesome-5',
        iconId: 'drink',
        iconColor: '#000000',
    },
    {
        id: 'e5035cc0-65d7-44ee-8a9f-67a9f3e8b1e6',
        tag: 'rockClimbing',
        categoryKey: 'interestsCategories.sports',
        displayNameKey: 'interests.sports.Climbing',
        emoji: '🧗‍♀️',
        iconGroup: 'font-awesome-5',
        iconId: 'futbol',
        iconColor: '#000000',
    },
    {
        id: 'e7d62ad0-d962-445c-a995-2f261caf09a6',
        tag: 'videoGamesComputer',
        categoryKey: 'interestsCategories.games',
        displayNameKey: 'interests.games.videoGamesComputer',
        emoji: '🖥️',
        iconGroup: 'font-awesome-5',
        iconId: 'futbol',
        iconColor: '#000000',
    },
    {
        id: 'e8541b7a-e45d-4588-ac68-757fbd4742f2',
        tag: 'nailCare',
        categoryKey: 'interestsCategories.fashion',
        displayNameKey: 'interests.fashion.nailCare',
        emoji: '💅',
        iconGroup: 'font-awesome-5',
        iconId: 'art',
        iconColor: '#000000',
    },
    {
        id: 'efae5148-973d-4d93-b077-0f2332218b93',
        tag: 'instruments',
        categoryKey: 'interestsCategories.arts',
        displayNameKey: 'interests.arts.instruments',
        emoji: '🎷',
        iconGroup: 'font-awesome-5',
        iconId: 'art',
        iconColor: '#000000',
    },
    {
        id: 'f4f1ff84-69c4-494e-876b-285416b5773e',
        tag: 'foodTrucks',
        categoryKey: 'interestsCategories.foodDrink',
        displayNameKey: 'interests.foodDrink.foodTrucks',
        emoji: '🚚',
        iconGroup: 'font-awesome-5',
        iconId: 'drink',
        iconColor: '#000000',
    },
    {
        id: 'f5a0896c-a656-49be-a2f7-1c3fd9789f50',
        tag: 'dance',
        categoryKey: 'interestsCategories.arts',
        displayNameKey: 'interests.arts.dance',
        emoji: '💃🏻',
        iconGroup: 'font-awesome-5',
        iconId: 'art',
        iconColor: '#000000',
    },
    {
        id: 'f81bb3e0-140a-4fa7-b674-4e3d12cdc9df',
        tag: 'schoolClubs',
        categoryKey: 'interestsCategories.business',
        displayNameKey: 'interests.business.schoolClubs',
        emoji: '🎒',
        iconGroup: 'font-awesome-5',
        iconId: 'business',
        iconColor: '#000000',
    },
    {
        id: 'fba711b3-4fce-4f38-90b8-ef0047415622',
        tag: 'boardGames',
        categoryKey: 'interestsCategories.games',
        displayNameKey: 'interests.games.boardGames',
        emoji: '🃏',
        iconGroup: 'font-awesome-5',
        iconId: 'futbol',
        iconColor: '#000000',
    },
    {
        id: 'feaddbe3-97ce-4ed8-8db3-412bfbdf8b3d',
        tag: 'basketball',
        categoryKey: 'interestsCategories.sports',
        displayNameKey: 'interests.sports.basketball',
        emoji: '🏀',
        iconGroup: 'font-awesome-5',
        iconId: 'futbol',
        iconColor: '#000000',
    },
    {
        id: 'fed86d7a-bc18-4684-810e-b708d8b6bdaa',
        tag: 'bikes',
        categoryKey: 'interestsCategories.travelTransport',
        displayNameKey: 'interests.travelTransport.bikes',
        emoji: '🏍️',
        iconGroup: 'font-awesome-5',
        iconId: 'futbol',
        iconColor: '#000000',
    },
];

exports.seed = async (knex) => {
    // Insert all interests with ON CONFLICT DO NOTHING to gracefully handle existing data
    const results = await Promise.all(
        interests.map((interest) => knex.raw(`
                INSERT INTO main.interests (id, tag, "categoryKey", "displayNameKey", emoji, "iconGroup", "iconId", "iconColor")
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT (id) DO NOTHING
            `, [
            interest.id,
            interest.tag,
            interest.categoryKey,
            interest.displayNameKey,
            interest.emoji,
            interest.iconGroup,
            interest.iconId,
            interest.iconColor,
        ])),
    );

    const inserted = results.filter((r) => r.rowCount > 0).length;
    const skipped = results.length - inserted;

    // eslint-disable-next-line no-console
    console.log(`Interests seed complete: ${inserted} inserted, ${skipped} skipped (already exist)`);
};
