apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: therr-network-tls
  namespace: default
spec:
  secretName: therr-network-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - 'therr.com'
    - 'www.therr.com'
    - 'dashboard.therr.com'
    - 'www.dashboard.therr.com'
    - 'api.therr.com'
    - 'www.api.therr.com'
    - 'websocket-service.therr.com'
    - 'www.websocket-service.therr.com'
    # Whitelabel
    - 'dashboard.appymeal.com'
    - 'www.dashboard.appymeal.com'
    - 'adsorchestra.com'
    - 'www.adsorchestra.com'
    - 'adsorchestrator.com'
    - 'www.adsorchestrator.com'
  duration: 4320h # 180d
  renewBefore: 720h # 30d
