apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: therr-network-rewrites-tls
  namespace: default
spec:
  secretName: therr-network-rewrites-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - 'go.therr.com'
    - 'link.therr.com'
    - 'www.go.therr.com'
    - 'www.link.therr.com'
  duration: 4320h # 180d
  renewBefore: 360h # 15d
