apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: therr-network-tls
  namespace: default
spec:
  secretName: therr-network-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: '*.therr.com'
  dnsNames:
    - 'therr.com'
    - '*.therr.com'
  duration: 2160h # 90d
  renewBefore: 720h # 30d
