apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-next-upstream: "error timeout http_502"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/use-gzip: "true"
    nginx.ingress.kubernetes.io/gzip-min-length: "1000"
    # nginx.ingress.kubernetes.io/proxy-read-timeout: “3600”
    # nginx.ingress.kubernetes.io/proxy-send-timeout: “3600”
    nginx.ingress.kubernetes.io/server-snippet: |
        gzip on;
        gzip_types      text/plain text/css text/js application/xml application/javascript;
        gzip_proxied    no-cache no-store private expired auth;
        gzip_min_length 1000;
        gzip_disable "MSIE [1-6]\.";
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 5;
        gzip_buffers 16 128k;

        if ($host ~ "link.therr.com|go.therr.com")
        {
            location /.well-known/acme-challenge/ {
                # Do nothing. nginx will serve response without rewrite
            }
            location / {
                rewrite ^ https://therr.com$request_uri permanent;
            }
        }

        if ($host ~ "www.link.therr.com|www.go.therr.com")
        {
            location /.well-known/acme-challenge/ {
                # Do nothing. nginx will serve response without rewrite
            }
            location / {
                rewrite ^ https://www.therr.com$request_uri permanent;
            }
        }
spec:
  tls:
  - hosts:
      - therr.com
      - www.therr.com
      - api.therr.com
      - www.api.therr.com
      - go.therr.com
      - www.go.therr.com
      - link.therr.com
      - www.link.therr.com
      - websocket-service.therr.com
      - www.websocket-service.therr.com
    secretName: therr-network-secret
  rules:
  - host: therr.com
    http:
      paths:
      - path: /?(.*)
        backend:
          service:
            name: client-cluster-ip-service
            port:
              number: 7070
        pathType: ImplementationSpecific
  - host: www.therr.com
    http:
      paths:
      - path: /?(.*)
        backend:
          service:
            name: client-cluster-ip-service
            port:
              number: 7070
        pathType: ImplementationSpecific
  - host: api.therr.com
    http:
      paths:
      - path: /?(.*)
        backend:
          service:
            name: api-gateway-service-loadbalancer-service
            port:
              number: 7770
        pathType: ImplementationSpecific
  - host: www.api.therr.com
    http:
      paths:
      - path: /?(.*)
        backend:
          service:
            name: api-gateway-service-loadbalancer-service
            port:
              number: 7770
        pathType: ImplementationSpecific
  - host: go.therr.com
    http:
      paths:
      - path: /?(.*)
        backend:
          service:
            name: client-cluster-ip-service
            port:
              number: 7070
        pathType: ImplementationSpecific
  - host: www.go.therr.com
    http:
      paths:
      - path: /?(.*)
        backend:
          service:
            name: client-cluster-ip-service
            port:
              number: 7070
        pathType: ImplementationSpecific
  - host: link.therr.com
    http:
      paths:
      - path: /?(.*)
        backend:
          service:
            name: client-cluster-ip-service
            port:
              number: 7070
        pathType: ImplementationSpecific
  - host: www.link.therr.com
    http:
      paths:
      - path: /?(.*)
        backend:
          service:
            name: client-cluster-ip-service
            port:
              number: 7070
        pathType: ImplementationSpecific
  - host: websocket-service.therr.com
    http:
      paths:
      - path: /?(.*)
        backend:
          service:
            name: websocket-service-cluster-ip-service
            port:
              number: 7743
        pathType: ImplementationSpecific
  - host: www.websocket-service.therr.com
    http:
      paths:
      - path: /?(.*)
        backend:
          service:
            name: websocket-service-cluster-ip-service
            port:
              number: 7743
        pathType: ImplementationSpecific
          