apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: default
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "info@therr.com"
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
      selector:
        dnsZones:
        - 'therr.com'
        - '*.therr.com'
        # Whitelabel
        - 'dashboard.appymeal.com'
        - '*.dashboard.appymeal.com'
        - 'adsorchestra.com'
        - '*.adsorchestra.com'
        - 'adsorchestrator.com'
        - '*.adsorchestrator.com'
