apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: push-notifications-service-pdb
  namespace: default
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      component: server-push-notifications
