apiVersion: apps/v1
kind: Deployment
metadata:
  name: push-notifications-service-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      component: server-push-notifications
  template:
    metadata:
      labels:
        component: server-push-notifications
        tier: microservices
        layer: services-internal
    spec:
      serviceAccountName: therr-k8s-service-account
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: Exists
            weight: 100
      nodeSelector:
        cloud.google.com/gke-preemptible: "true"
      containers:
      - name: server-push-notifications
        image: therrapp/push-notifications-service:latest
        resources:
          limits:
            memory: "192Mi"
            cpu: "100m"
        ports:
        - containerPort: 7775
        env:
        - name: PUSH_NOTIFICATIONS_SERVICE_API_PORT
          value: "7775"
        - name: URI_WHITELIST
          value: "https://therr.com,https://www.therr.com"
        - name: HONEYCOMB_API_KEY
          valueFrom:
            secretKeyRef:
              name: honeycomb-writekey
              key: HONEYCOMB
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: LOG_LEVEL
          value: "info"
        - name: DB_USER_MAIN_WRITE
          value: "therrAppUser"
        - name: DB_HOST_MAIN_WRITE
          value: "127.0.0.1"
        - name: DB_PORT_MAIN_WRITE
          value: "5432"
        - name: DB_PASSWORD_MAIN_WRITE
          valueFrom:
            secretKeyRef:
              name: db-password-app
              key: DB_PASSWORD_APP_WRITE
        - name: DB_USER_MAIN_READ
          value: "therrAppUser"
        - name: DB_HOST_MAIN_READ
          value: "127.0.0.1"
        - name: DB_PORT_MAIN_READ
          value: "5432"
        - name: DB_PASSWORD_MAIN_READ
          valueFrom:
            secretKeyRef:
              name: db-password-app
              key: DB_PASSWORD_APP_READ
        - name: PUSH_NOTIFICATIONS_GOOGLE_CREDENTIALS_BASE64
          valueFrom:
            secretKeyRef:
              name: push-notifications-google-app-credentials
              key: PUSH_NOTIFICATIONS_GOOGLE_APP_CREDENTIALS
        - name: MAPS_SERVICE_DATABASE
          value: "therr_maps_service_db"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: therrjwtsecret
              key: THERRJWT_SECRET
        - name: REDIS_GENERIC_HOST
          value: "redis-cluster-ip-service"
        - name: REDIS_GENERIC_PORT
          value: "6379"
      - name: cloud-sql-proxy
        # It is recommended to use the latest version of the Cloud SQL proxy
        # Make sure to update on a regular schedule!
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.3
        args:
          # If connecting from a VPC-native GKE cluster, you can use the
          # following flag to have the proxy connect over private IP
          - "--private-ip"

          # Enable structured logging with LogEntry format:
          - "--structured-logs"

          # Replace DB_PORT with the port the proxy should listen on
          - "--port=5432"
          - "therr-app:us-central1:therr-db-main-prod-14"
        securityContext:
          # The default Cloud SQL proxy image runs as the
          # "nonroot" user and group (uid: 65532) by default.
          runAsNonRoot: true
            # You should use resource requests/limits as a best practice to prevent
            # pods from consuming too many resources and affecting the execution of
            # other pods. You should adjust the following values based on what your
            # application needs. For details, see
            # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            # The proxy's memory use scales linearly with the number of active
            # connections. Fewer open connections will use less memory. Adjust
            # this value based on your application's requirements.
            memory: "64Mi"
            # The proxy's CPU use scales linearly with the amount of IO between
            # the database and the application. Adjust this value based on your
            # application's requirements.
            cpu: "50m"
