/**
 * Guide content loader.
 *
 * Posts are static JSON in `src/content/guides/*.json`, generated by the
 * `scripts/generate-content` CLI. Webpack `require.context` bundles all of
 * them at build time into both the client and SSR bundles, so lookups are
 * synchronous on either side.
 *
 * Types here mirror `scripts/generate-content/utils/contentSchema.ts` — keep
 * the two in sync. We duplicate rather than cross-import to keep each
 * tsconfig hermetic (scripts/ has its own rootDir).
 */
import { Categories } from 'therr-js-utilities/constants';

export type PostType = 'list' | 'data' | 'mixed';
export type PostStatus = 'draft' | 'published';
export type PostLocale = 'es' | 'fr-ca';

export interface IPostHeroImage {
    url: string;
    alt: string;
    credit?: string;
}

export interface IPostMetadata {
    slug: string;
    type: PostType;
    status: PostStatus;
    title: string;
    description: string;
    city?: string;
    category?: string;
    publishedAt: string;
    updatedAt: string;
    author: string;
    authorUrl?: string;
    heroImage?: IPostHeroImage;
}

export interface ISpaceListItem {
    spaceId: string;
    rank: number;
    blurb: string;
    reason?: string;
}

export type IPostSection =
    | { type: 'prose'; body: string }
    | { type: 'space-list'; items: ISpaceListItem[] }
    | { type: 'data-callout'; stat: string; statLabel: string; body?: string }
    | { type: 'data-table'; caption: string; headers: string[]; rows: (string | number)[][] }
    | { type: 'faq'; items: { question: string; answer: string }[] }
    | { type: 'cta'; heading: string; body: string; href?: string; ctaText?: string };

export interface IPostLocaleContent {
    title: string;
    description: string;
    lead: string;
    sections: IPostSection[];
}

export interface IPost extends IPostMetadata {
    lead: string;
    sections: IPostSection[];
    locales?: Partial<Record<PostLocale, IPostLocaleContent>>;
}

interface IGuideManifest {
    bySlug: Record<string, IPost>;
    all: IPost[];
}

function loadManifest(): IGuideManifest {
    const bySlug: Record<string, IPost> = {};
    try {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const ctx: any = (require as any).context('../content/guides', false, /^\.\/(?!index\.json$).+\.json$/);
        ctx.keys().forEach((key: string) => {
            const post = ctx(key) as IPost;
            if (post && post.slug) bySlug[post.slug] = post;
        });
    } catch {
        // require.context not available (e.g., unit tests with jest); fall back to empty manifest.
    }
    const all = Object.values(bySlug).sort((a, b) => (b.publishedAt || '').localeCompare(a.publishedAt || ''));
    return { bySlug, all };
}

const manifest = loadManifest();

export function getGuide(slug: string): IPost | null {
    return manifest.bySlug[slug] || null;
}

export function getAllGuides(): IPost[] {
    return manifest.all;
}

export function getPublishedGuides(): IPost[] {
    return manifest.all.filter((p) => p.status === 'published');
}

export function getGuidesByCity(citySlug: string): IPost[] {
    return getPublishedGuides().filter((p) => p.city === citySlug);
}

export function getGuidesByCategory(categorySlug: string): IPost[] {
    // URL uses short slugs ("bars"), posts store full category keys
    // ("categories.bar/drinks") — translate before filtering.
    const categoryKey = Categories.SlugToCategoryMap[categorySlug] || categorySlug;
    return getPublishedGuides().filter((p) => p.category === categoryKey);
}

/** URL slug for a post's category, suitable for /guides/category/<slug>. */
export function getCategoryUrlSlug(categoryKey?: string): string | undefined {
    if (!categoryKey) return undefined;
    return Categories.CategorySlugMap[categoryKey];
}

export function getGuidesBySpaceId(spaceId: string): IPost[] {
    return getPublishedGuides().filter((p) => p.sections.some(
        (s) => s.type === 'space-list' && s.items.some((i) => i.spaceId === spaceId),
    ));
}

/**
 * Returns the locale-resolved view of a post: title, description, lead,
 * sections — falling back to the default-locale (en-us) values when the
 * requested locale is not present.
 */
export interface IResolvedPost {
    metadata: IPostMetadata;
    title: string;
    description: string;
    lead: string;
    sections: IPostSection[];
}

export function resolveGuideForLocale(post: IPost, locale: string): IResolvedPost {
    const isLocale = (l: string): l is PostLocale => l === 'es' || l === 'fr-ca';
    const localized = isLocale(locale) ? post.locales?.[locale] : undefined;
    return {
        metadata: {
            slug: post.slug,
            type: post.type,
            status: post.status,
            title: post.title,
            description: post.description,
            city: post.city,
            category: post.category,
            publishedAt: post.publishedAt,
            updatedAt: post.updatedAt,
            author: post.author,
            authorUrl: post.authorUrl,
            heroImage: post.heroImage,
        },
        title: localized?.title || post.title,
        description: localized?.description || post.description,
        lead: localized?.lead || post.lead,
        sections: localized?.sections || post.sections,
    };
}
