apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: server-api-gateway
  ports:
  - port: 7770
    targetPort: 7770
