apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server-api-gateway
  template:
    metadata:
      labels:
        component: server-api-gateway
    spec:
      containers:
      - name: server-api-gateway
        image: therrapp/api-gateway:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "75m"
        ports:
        - containerPort: 7770
        env:
        - name: API_GATEWAY_PORT
          value: "7770"
        - name: URI_WHITELIST
          value: "https://therr.app,https://www.therr.app"
        - name: HONEYCOMB_API_KEY
          valueFrom:
            secretKeyRef:
              name: honeycomb-writekey
              key: HONEYCOMB
        - name: LOG_LEVEL
          value: "info"
        - name: LOGGING_DATASET
          value: "production"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: therrjwtsecret
              key: THERRJWT_SECRET