apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: rili-world-tls
spec:
  secretName: rili-world-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: rili.world
  dnsNames:
    - rili.world
    - www.rili.world