apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: rili-network-tls
spec:
  secretName: rili-network
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: rili.network
  dnsNames:
    - rili.network
    - www.rili.network