apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: therr-network-tls
spec:
  secretName: therr-network
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: therr.app
  dnsNames:
    - therr.app
    - www.therr.app