apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: client
        image: riliadmin/client-web:0492893e2ded702ca6f1defa9a65e923d00ae479
        ports:
        - containerPort: 7070
        env:
          - name: API_PORT
            value: "7770"
          - name: CLIENT_PORT
            value: "7070"
          - name: HONEYCOMB_API_KEY
            valueFrom:
              secretKeyRef:
                name: honeycomb-writekey
                key: key
          - name: LOG_LEVEL
            value: "info"
          - name: SOCKET_PORT
            value: "7743"
