apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: client
        image: riliadmin/client-web:eadc9ee7feff5d1d0a72be84d0fb88c634c37e46
        ports:
        - containerPort: 7070
        env:
          - name: API_PORT
            value: "7770"
          - name: CLIENT_PORT
            value: "7070"
          - name: SOCKET_PORT
            value: "7743"
