apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: client
        image: riliadmin/client-web:79f99fb9b51c54c1a19af245ca526c2f69ca5cfe
        ports:
        - containerPort: 7070
        env:
          - name: API_PORT
            value: "7770"
          - name: CLIENT_PORT
            value: "7070"
          - name: SOCKET_PORT
            value: "7743"
