apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: client
        image: riliadmin/client-web:0d8c3892631b4600a2c87f73624d8b792c97dc4b
        ports:
        - containerPort: 7070
        env:
          - name: API_PORT
            value: "7770"
          - name: CLIENT_PORT
            value: "7070"
          - name: SOCKET_PORT
            value: "7743"
