apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    component: web
    type: microservice
    layer: service-frontend
  ports:
  - port: 7070
    targetPort: 7070
