apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: client
        image: riliadmin/client-web:629bfb2c319a1d92dd58ac30533eceadf0a16eab
        imagePullPolicy: Always
        ports:
        - containerPort: 7070
        env:
          - name: API_PORT
            value: "7770"
          - name: CLIENT_PORT
            value: "7070"
          - name: LOG_LEVEL
            value: "info"
          - name: SOCKET_PORT
            value: "7743"
