apiVersion: v1
kind: Service
metadata:
  name: maps-service-cluster-ip-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: ClusterIP
  selector:
    component: server-maps
  ports:
  - port: 7773
    targetPort: 7773
