apiVersion: v1
kind: Service
metadata:
  name: messages-service-cluster-ip-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    component: server
  ports:
  - port: 7771
    targetPort: 7771
