apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server-messages
  template:
    metadata:
      labels:
        component: server-messages
    spec:
      containers:
      - name: server-messages
        image: therrapp/messages-service:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
        ports:
        - containerPort: 7772
        env:
        - name: MESSAGES_SERVICE_API_PORT
          value: "7772"
        - name: URI_WHITELIST
          value: "https://therr.app,https://www.therr.app"
        - name: HONEYCOMB_API_KEY
          valueFrom:
            secretKeyRef:
              name: honeycomb-writekey
              key: HONEYCOMB
        - name: LOG_LEVEL
          value: "info"
        - name: LOGGING_DATASET
          value: "production"
        - name: DB_USER_MAIN_WRITE
          value: "postgres"
        - name: DB_HOST_MAIN_WRITE
          value: "therr-db-main-us-east-2.chtozlwlmzlk.us-east-2.rds.amazonaws.com"
        - name: DB_PORT_MAIN_WRITE
          value: "5432"
        - name: DB_PASSWORD_MAIN_WRITE
          valueFrom:
            secretKeyRef:
              name: dbpasswordmainwrite
              key: DBPASSWORD_MAINWRITE
        - name: DB_USER_MAIN_READ
          value: "postgres"
        - name: DB_HOST_MAIN_READ
          value: "therr-db-main-us-east-2.chtozlwlmzlk.us-east-2.rds.amazonaws.com"
        - name: DB_PORT_MAIN_READ
          value: "5432"
        - name: DB_PASSWORD_MAIN_READ
          valueFrom:
            secretKeyRef:
              name: dbpasswordmainread
              key: DBPASSWORD_MAINREAD
        - name: MESSAGES_SERVICE_DATABASE
          value: "therr_messages_service_db"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: therrjwtsecret
              key: THERRJWT_SECRET