apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server-messages
  template:
    metadata:
      labels:
        component: server-messages
    spec:
      containers:
      - name: server-messages
        image: therrapp/messages-service:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
        ports:
        - containerPort: 7772
        env:
        - name: MESSAGES_SERVICE_API_PORT
          value: "7772"
        - name: URI_WHITELIST
          value: "https://therr.app,https://www.therr.app"
        - name: HONEYCOMB_API_KEY
          valueFrom:
            secretKeyRef:
              name: honeycomb-writekey
              key: HONEYCOMB
        - name: LOG_LEVEL
          value: "info"
        - name: LOGGING_DATASET
          value: "production"
        - name: PG_USER
          value: "postgres"
        - name: PG_HOST
          value: "postgres-cluster-ip-service"
        - name: PG_PORT
          value: "5432"
        - name: MESSAGES_SERVICE_PG_DATABASE
          value: "therr_messages"
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgpassword
              key: PGPASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: therrjwtsecret
              key: THERRJWT_SECRET