apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
      - name: server
        image: riliadmin/messages-service:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 7771
        env:
        - name: MESSAGES_SERVICE_API_PORT
          value: "7771"
        - name: URI_WHITELIST
          value: "https://rili.world"
        - name: HONEYCOMB_API_KEY
          valueFrom:
            secretKeyRef:
              name: honeycomb-writekey
              key: key
        - name: LOG_LEVEL
          value: "info"
        - name: PG_USER
          value: "postgres"
        - name: PG_HOST
          value: "postgres-cluster-ip-service"
        - name: PG_PORT
          value: "5432"
        - name: MESSAGES_SERVICE_PG_DATABASE
          value: "rili_messages"
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgpassword
              key: PGPASSWORD
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: riliapisecret
              key: RILIAPISECRET