apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
      - name: server
        image: riliadmin/server-api:0d8c3892631b4600a2c87f73624d8b792c97dc4b
        ports:
        - containerPort: 7770
        env:
        - name: API_PORT
          value: "7770"
        - name: CLIENT_URI
          value: "https://rili.live"
        - name: PG_USER
          value: "postgres"
        - name: PG_HOST
          value: "postgres-cluster-ip-service"
        - name: PG_PORT
          value: "5432"
        - name: PG_DATABASE
          value: "postgres"
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgpassword
              key: PGPASSWORD
        - name: REDIS_PUB_HOST
          value: "redis-cluster-ip-service"
        - name: REDIS_PUB_PORT
          value: "6379"
        - name: SECRET
          value: "this-should-be-an-actual-secret"