apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
      - name: server
        image: riliadmin/rili-server-api
        ports:
        - containerPort: 7770
        env:
        - name: REDIS_HOST
          value: "redis-cluster-ip-service"
        - name: REDIS_PORT
          value: "6379"
        - name: PG_USER
          value: "postgres"
        - name: PG_HOST
          value: "postgres-cluster-ip-service"
        - name: PG_PORT
          value: "5432"
        - name: PG_DATABASE
          value: "postgres"
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgpassword
              key: PGPASSWORD