apiVersion: v1
kind: Service
metadata:
  name: users-service-cluster-ip-service
  namespace: default
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    component: server-users
  ports:
  - port: 7771
    targetPort: 7771