apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
      - name: server
        image: riliadmin/users-service:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 7770
        env:
        - name: API_PORT
          value: "7770"
        - name: URI_WHITELIST
          value: "https://rili.world"
        - name: HONEYCOMB_API_KEY
          valueFrom:
            secretKeyRef:
              name: honeycomb-writekey
              key: key
        - name: LOG_LEVEL
          value: "info"
        - name: PG_USER
          value: "postgres"
        - name: PG_HOST
          value: "postgres-cluster-ip-service"
        - name: PG_PORT
          value: "5432"
        - name: PG_DATABASE
          value: "rili_prod"
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgpassword
              key: PGPASSWORD
        - name: REDIS_NODE_ONE_HOST
          value: "redis-cluster-ip-service"
        - name: REDIS_NODE_ONE_PORT
          value: "6379"
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: riliapisecret
              key: RILIAPISECRET