apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server-users
  template:
    metadata:
      labels:
        component: server-users
        tier: microservices
    spec:
      containers:
      - name: server-users
        image: therrapp/users-service:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 7771
        env:
        - name: AWS_SES_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-ses-access-key-id
              key: AWSSESACCESSKEYID
        - name: AWS_SES_ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: aws-ses-access-key-secret
              key: AWSSESACCESSKEYSECRET
        - name: AWS_SES_REGION
          value: "us-east-2"
        - name: AWS_SES_FROM_EMAIL
          value: "therr.main@gmail.com"
        - name: USERS_SERVICE_API_PORT
          value: "7771"
        - name: URI_WHITELIST
          value: "https://therr.app,https://www.therr.app"
        - name: HONEYCOMB_API_KEY
          valueFrom:
            secretKeyRef:
              name: honeycomb-writekey
              key: HONEYCOMB
        - name: LOG_LEVEL
          value: "info"
        - name: LOGGING_DATASET
          value: "production"
        - name: REDIS_PUB_HOST
          value: "redis-cluster-ip-service"
        - name: REDIS_PUB_PORT
          value: "6379"
        - name: DB_USER_MAIN_WRITE
          value: "app"
        - name: DB_HOST_MAIN_WRITE
          value: "db-write-us-east-2-main.therr.app"
        - name: DB_PORT_MAIN_WRITE
          value: "5432"
        - name: DB_PASSWORD_MAIN_WRITE
          valueFrom:
            secretKeyRef:
              name: dbpasswordappwrite
              key: DBPASSWORD_APPWRITE
        - name: DB_USER_MAIN_READ
          value: "app"
        - name: DB_HOST_MAIN_READ
          value: "db-write-us-east-2-main.therr.app"
        - name: DB_PORT_MAIN_READ
          value: "5432"
        - name: DB_PASSWORD_MAIN_READ
          valueFrom:
            secretKeyRef:
              name: dbpasswordappread
              key: DBPASSWORD_APPREAD
        - name: USERS_SERVICE_DATABASE
          value: "therr_users_service_db"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: therrjwtsecret
              key: THERRJWT_SECRET