apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server-users
  template:
    metadata:
      labels:
        component: server-users
    spec:
      containers:
      - name: server-users
        image: therrapp/users-service:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "75m"
        ports:
        - containerPort: 7771
        env:
        - name: AWS_SES_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-ses-access-key-id
              key: AWSSESACCESSKEYID
        - name: AWS_SES_ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: aws-ses-access-key-secret
              key: AWSSESACCESSKEYSECRET
        - name: AWS_SES_REGION
          value: "us-east-2"
        - name: USERS_SERVICE_API_PORT
          value: "7771"
        - name: URI_WHITELIST
          value: "https://therr.app,https://www.therr.app"
        - name: HONEYCOMB_API_KEY
          valueFrom:
            secretKeyRef:
              name: honeycomb-writekey
              key: HONEYCOMB
        - name: LOG_LEVEL
          value: "info"
        - name: LOGGING_DATASET
          value: "production"
        - name: REDIS_NODE_ONE_HOST
          value: "redis-cluster-ip-service"
        - name: REDIS_NODE_ONE_PORT
          value: "6379"
        - name: PG_USER
          value: "postgres"
        - name: PG_HOST
          value: "postgres-cluster-ip-service"
        - name: PG_PORT
          value: "5432"
        - name: USERS_SERVICE_PG_DATABASE
          value: "therr_users"
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgpassword
              key: PGPASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: therrjwtsecret
              key: THERRJWT_SECRET