apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: users-service-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      component: server-users
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchExpressions:
          - { key: component, operator: In, values: [server-api-gateway, server-websocket, server-maps] }