apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
      - name: server
        image: riliadmin/websocket-service:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 7743
        env:
        - name: MESSAGES_SERVICE_API_PORT
          value: "7771"
        - name: HONEYCOMB_API_KEY
          valueFrom:
            secretKeyRef:
              name: honeycomb-writekey
              key: key
        - name: LOG_LEVEL
          value: "info"
        - name: REDIS_NODE_ONE_HOST
          value: "redis-cluster-ip-service"
        - name: REDIS_NODE_ONE_PORT
          value: "6379"
        - name: SOCKET_PORT
          value: "7743"
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: riliapisecret
              key: RILIAPISECRET