const INITIAL_LATIUDE_DELTA = 0.00122;
const INITIAL_LONGITUDE_DELTA = 0.00051;
const MIN_LOAD_TIMEOUT = 250;
const DEFAULT_MOMENT_PROXIMITY = 25;
const MIN_ZOOM_LEVEL = 5;
const MOMENTS_REFRESH_THROTTLE_MS = 10 * 1000;

export {
    INITIAL_LATIUDE_DELTA,
    INITIAL_LONGITUDE_DELTA,
    MIN_LOAD_TIMEOUT,
    DEFAULT_MOMENT_PROXIMITY,
    MIN_ZOOM_LEVEL,
    MOMENTS_REFRESH_THROTTLE_MS,
};
