version: '3'

services:
  rili-nginx:
    build:
      context: ../
      dockerfile: docker/dev.nginx.Dockerfile
    ports:
      - 80:80
    environment:
      - NGINX_HOST=rili.live
      - NGINX_PORT=80
  web-dev:
    image: httpd
    volumes:
      - ../rili-client-web/build:/usr/local/apache2/htdocs/
  rili-client-web:
    build:
      context: ../
      dockerfile: docker/rili-client-web.Dockerfile
    ports:
      - 7070:7070
  rili-server-api:
    build:
      context: ../
      dockerfile: docker/rili-server-api.Dockerfile
    ports:
      - 7770:7770
  rili-server-socket:
    build:
      context: ../
      dockerfile: docker/rili-server-socket.Dockerfile
    ports:
      - 7743:7743
  rili-postgres-dev:
    image: postgres:latest
    ports:
      - 7432:5432
    environment:
      - POSTGRES_USER=riliAdmin
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
  rili-redis-pub-dev:
    image: redis:latest
    ports:
      - 17771:6379
  rili-redis-sub-dev:
    image: redis:latest
    ports:
      - 17772:6379