version: '3.7'

services:
  rili-nginx:
    image: riliadmin/rili-nginx:test
    environment:
      - NGINX_HOST=rest.rili.live
    volumes:
      - ./volumes/nginx.test.conf:/etc/nginx/nginx.conf
  rili-client-web:
    image: riliadmin/rili-client-web:test
    build:
      args:
        - NODE_ENV=test
    environment:
      - NODE_ENV=test
  rili-server-api:
    image: riliadmin/rili-server-api:test
    build:
      args:
        - NODE_ENV=test
    environment:
      - NODE_ENV=test
  rili-server-socket:
    image: riliadmin/rili-server-socket:test
    build:
      args:
        - NODE_ENV=test
    environment:
      - NODE_ENV=test