version: '3.6'

services:
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - rili-network
  rili-nginx:
    restart: always
    build:
      context: ../
      dockerfile: docker/Dockerfile.nginx
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_PORT=80
    volumes:
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/certbot
    networks:
      - rili-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  rili-client-web:
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./rili-client-web/Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION}
    ports:
      - 7070:7070
    environment:
      - CLIENT_PORT
      - CLIENT_URI
      - DOMAIN_CERT_LOCATION
      - DOMAIN_KEY_LOCATION
      - NODE_VERSION
      - PG_DATABASE
      - PG_HOST
      - PG_PASSWORD
      - PG_PORT
      - PG_USER
      - SECRET
    volumes:
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/certbot
    networks:
      - rili-network
  rili-server-api:
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./rili-server-api/Dockerfile.api
      args:
        - NODE_VERSION=${NODE_VERSION}
    ports:
      - 7770:7770
    environment:
      - CLIENT_PORT
      - CLIENT_URI
      - DOMAIN_CERT_LOCATION
      - DOMAIN_KEY_LOCATION
      - NODE_VERSION
      - PG_DATABASE
      - PG_HOST
      - PG_PASSWORD
      - PG_PORT
      - PG_USER
      - SECRET
    volumes:
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/certbot
    networks:
      - rili-network
  rili-server-socket:
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./rili-server-socket/Dockerfile.socket
      args:
        - NODE_VERSION=${NODE_VERSION}
    ports:
      - 7743:7743
    environment:
      - CLIENT_PORT
      - CLIENT_URI
      - DOMAIN_CERT_LOCATION
      - DOMAIN_KEY_LOCATION
      - NODE_VERSION
      - PG_DATABASE
      - PG_HOST
      - PG_PASSWORD
      - PG_PORT
      - PG_USER
      - SECRET
    networks:
      - rili-network
    depends_on:
      - rili-redis-pub
      - rili-redis-sub
  rili-redis-pub:
    image: redis:5
    restart: unless-stopped
    deploy:
      replicas: 1
      update_config:
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - 17771:6379
    networks:
      - rili-network
  rili-redis-sub:
    image: redis:5
    restart: unless-stopped
    deploy:
      replicas: 1
      update_config:
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - 17772:6379
    networks:
      - rili-network

networks:
  rili-network:
    driver: overlay
    attachable: true
