version: '3.6'

services:
  rili-nginx:
    image: rili/nginx-dev
    environment:
        - NGINX_HOST=dev.rili.live
    volumes:
      - ./volumes/nginx.dev.conf:/etc/nginx/nginx.conf
  rili-client-web:
    image: rili/client-web-dev
    build:
      dockerfile: ./rili-client-web/Dockerfile.dev
      args:
        - NODE_ENV=development
        - NODE_RUNNER=nodemon
    environment:
      - NODE_ENV=development
    volumes:
      - ../.env:/usr/src/app/.env
      - ../rili-client-web/build:/usr/src/app/build/
      - ../rili-client-web/src/views:/usr/src/app/src/views/
  rili-postgres:
    image: postgres:11
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - 7432:5432
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    networks:
      - rili-network
  rili-server-api:
    image: rili/server-api-dev
    build:
      dockerfile: ./rili-server/Dockerfile.api.dev
      args:
        - NODE_ENV=development
        - NODE_RUNNER=nodemon
    environment:
      - NODE_ENV=development
    volumes:
      - ../.env:/usr/src/app/.env
      - ../rili-server/build:/usr/src/app/build/
  rili-server-socket:
    image: rili/server-socket-dev
    build:
      dockerfile: ./rili-server/Dockerfile.socket.dev
      args:
        - NODE_ENV=development
        - NODE_RUNNER=nodemon
    environment:
      - NODE_ENV=development
    volumes:
      - ../.env:/usr/src/app/.env
      - ../rili-server/build:/usr/src/app/build/