version: '3'

services:
  rili-nginx:
    build:
      context: ../
      dockerfile: docker/prod.nginx.Dockerfile
    image: rili-nginx
    ports:
      - 80:80
    environment:
      - NGINX_HOST=rili.live
      - NGINX_PORT=80
  rili-postgres:
    image: postgres:latest
    ports:
      - 7432:5432
    environment:
      - POSTGRES_USER=riliAdmin
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
  rili-redis-pub:
    image: redis:latest
    ports:
      - 17771:6379
  rili-redis-sub:
    image: redis:latest
    ports:
      - 17772:6379