version: '3.6'

services:
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - rili-network
  rili-nginx:
    image: rili/nginx
    environment:
      - NGINX_HOST=rili.live
    volumes:
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/certbot
      - ./volumes/nginx.prod.conf:/etc/nginx/nginx.conf
  rili-client-web:
    image: rili/client-web
    build:
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    volumes:
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/certbot
  rili-server-api:
    image: rili/server-api
    build:
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    volumes:
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/certbot
  rili-server-socket:
    image: rili/server-socket
    build:
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production