version: '3.7'

services:
  rili-nginx:
    environment:
      - NGINX_HOST=stage.rili.live
    volumes:
      - ./volumes/nginx.stage.conf:/etc/nginx/nginx.conf
  rili-client-web:
    build:
      args:
        - NODE_ENV=stage
    environment:
      - NODE_ENV=stage
  rili-server-api:
    build:
      args:
        - NODE_ENV=stage
    environment:
      - NODE_ENV=stage
  rili-server-socket:
    build:
      args:
        - NODE_ENV=stage
    environment:
      - NODE_ENV=stage