services:
  rili-client-web:
    build:
      context: /Users/zanselm/hobby/rili/codebase/rili-app
      dockerfile: docker/rili-client-web.Dockerfile
    ports:
    - 7070:7070/tcp
  rili-nginx:
    build:
      context: /Users/zanselm/hobby/rili/codebase/rili-app
      dockerfile: docker/prod.nginx.Dockerfile
    environment:
      NGINX_HOST: rili.live
      NGINX_PORT: '80'
    image: rili-nginx
    ports:
    - 80:80/tcp
  rili-postgres:
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: riliAdmin
    image: postgres:latest
    ports:
    - 7432:5432/tcp
    volumes:
    - /Users/zanselm/hobby/rili/codebase/rili-app/docker/volumes/postgres-data:/var/lib/postgresql/data:rw
  rili-postgres-dev:
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: riliAdmin
    image: postgres:latest
    ports:
    - 7432:5432/tcp
    volumes:
    - /Users/zanselm/hobby/rili/codebase/rili-app/docker/volumes/postgres-data:/var/lib/postgresql/data:rw
  rili-redis-pub:
    image: redis:latest
    ports:
    - 17771:6379/tcp
  rili-redis-pub-dev:
    image: redis:latest
    ports:
    - 17771:6379/tcp
  rili-redis-sub:
    image: redis:latest
    ports:
    - 17772:6379/tcp
  rili-redis-sub-dev:
    image: redis:latest
    ports:
    - 17772:6379/tcp
  rili-server-api:
    build:
      context: /Users/zanselm/hobby/rili/codebase/rili-app
      dockerfile: docker/rili-server-api.Dockerfile
    ports:
    - 7770:7770/tcp
  rili-server-socket:
    build:
      context: /Users/zanselm/hobby/rili/codebase/rili-app
      dockerfile: docker/rili-server-socket.Dockerfile
    ports:
    - 7743:7743/tcp
  web-dev:
    image: httpd
    volumes:
    - /Users/zanselm/hobby/rili/codebase/rili-app/rili-client-web/build:/usr/local/apache2/htdocs:rw
version: '3.0'

