/* eslint-disable max-len */
const CategoriesMap: {
    [key: number]: string;
} = {
    1: 'categories.uncategorized',
    2: 'categories.storefront/shop',
    3: 'categories.restaurant/food',
    4: 'categories.bar/drinks',
    5: 'categories.marketplace/festival',
    6: 'categories.artwork/expression',
    7: 'categories.music/concerts',
    8: 'categories.nature/parks',
    9: 'categories.hotels/lodging',
    10: 'categories.event/space',
    11: 'categories.art', // remove
    12: 'categories.gaming',
    13: 'categories.geocache',
    14: 'categories.menu',
    15: 'categories.music', // remove
    16: 'categories.deals',
    17: 'categories.fitness', // remove
    18: 'categories.storefront', // remove
    19: 'categories.idea',
    20: 'categories.food', // remove
    21: 'categories.nature', // remove
    22: 'categories.travel',
    23: 'categories.warning',
    24: 'categories.seasonal',
    25: 'categories.drinks',
    26: 'categories.nightLife',
    27: 'categories.sports', // remove
    28: 'categories.fitness/sports',
    29: 'categories.museum/academia',
};

const CategoryToInterestsMap = {
    [CategoriesMap[2]]: [
        'interests.business.localBusiness',
    ],
    [CategoriesMap[3]]: [
        'interests.foodDrink.dining',
        'interests.foodDrink.happyHour',
        'interests.foodDrink.desserts',
        'interests.foodDrink.foodTrucks',
        'interests.foodDrink.ramen',
        'interests.foodDrink.veganFood',
    ],
    [CategoriesMap[4]]: [
        'interests.foodDrink.cocktails',
        'interests.foodDrink.happyHour',
        'interests.foodDrink.coffee',
        'interests.foodDrink.juiceSmoothies',
    ],
    [CategoriesMap[5]]: [
        'interests.arts.visualArts',
        'interests.arts.liveMusic',
    ],
    [CategoriesMap[6]]: [
        'interests.arts.painting',
        'interests.arts.visualArts',
        'interests.arts.anime',
        'interests.arts.photography',
        'interests.arts.crafts',
        'interests.arts.drawing',
        'interests.arts.digitalArt',
        'interests.arts.textileArt',
        'interests.arts.dance',
        'interests.arts.instruments',
        'interests.arts.liveMusic',
        'interests.arts.singing',
        'interests.arts.comedy',
        'interests.arts.reading',
    ],
    [CategoriesMap[7]]: [
        'interests.arts.instruments',
        'interests.arts.liveMusic',
        'interests.arts.singing',
        'interests.foodDrink.happyHour',
    ],
    [CategoriesMap[8]]: [
        'interests.sports.running',
        'interests.sports.cycling',
        'interests.sports.soccer',
        'interests.sports.Climbing',
    ],
    [CategoriesMap[9]]: [
        'interests.business.businessTravel',
        'interests.travelTransport.travel',
    ],
    [CategoriesMap[10]]: [
        'interests.business.localBusiness',
        'interests.arts.liveMusic',
        'interests.sports.baseball',
        'interests.sports.basketball',
        'interests.sports.football',
        'interests.sports.soccer',
        'interests.sports.hockey',
    ],
    [CategoriesMap[11]]: [
        'interests.arts.painting',
        'interests.arts.visualArts',
        'interests.arts.anime',
        'interests.arts.photography',
        'interests.arts.crafts',
        'interests.arts.drawing',
        'interests.arts.digitalArt',
        'interests.arts.textileArt',
        'interests.arts.dance',
        'interests.arts.instruments',
        'interests.arts.liveMusic',
        'interests.arts.singing',
        'interests.arts.comedy',
        'interests.arts.reading',
    ],
    [CategoriesMap[12]]: [
        'interests.games.videoGamesConsole',
        'interests.games.videoGamesComputer',
        'interests.games.tableTopGames',
        'interests.games.boardGames',
    ],
    [CategoriesMap[13]]: [
        'interests.games.boardGames',
        'interests.travelTransport.travel',
    ],
    [CategoriesMap[14]]: [
        'interests.foodDrink.dining',
        'interests.foodDrink.happyHour',
        'interests.foodDrink.cocktails',
        'interests.foodDrink.coffee',
        'interests.foodDrink.desserts',
        'interests.foodDrink.foodTrucks',
        'interests.foodDrink.juiceSmoothies',
        'interests.foodDrink.ramen',
        'interests.foodDrink.veganFood',
    ],
    [CategoriesMap[15]]: [
        'interests.arts.instruments',
        'interests.arts.liveMusic',
        'interests.arts.singing',
        'interests.foodDrink.happyHour',
    ],
    [CategoriesMap[16]]: [
        'interests.business.localBusiness',
        'interests.business.restaurant',
    ],
    [CategoriesMap[17]]: [
        'interests.sports.gymWorkouts',
        'interests.sports.bowling',
        'interests.sports.Climbing',
        'interests.sports.rockClimbing',
        'interests.sports.cycling',
    ],
    [CategoriesMap[18]]: [
        'interests.business.localBusiness',
        'interests.fashion.styleTrends',
        'interests.fashion.clothingAccessories',
    ],
    [CategoriesMap[19]]: [
        'interests.arts.painting',
        'interests.arts.visualArts',
        'interests.arts.anime',
        'interests.arts.photography',
        'interests.arts.crafts',
        'interests.arts.drawing',
        'interests.arts.digitalArt',
        'interests.arts.textileArt',
        'interests.arts.dance',
        'interests.arts.instruments',
        'interests.arts.liveMusic',
        'interests.arts.singing',
        'interests.arts.comedy',
        'interests.arts.reading',
    ],
    [CategoriesMap[20]]: [
        'interests.foodDrink.dining',
        'interests.foodDrink.happyHour',
        'interests.foodDrink.desserts',
        'interests.foodDrink.foodTrucks',
        'interests.foodDrink.ramen',
        'interests.foodDrink.veganFood',
    ],
    [CategoriesMap[21]]: [
        'interests.sports.running',
        'interests.sports.cycling',
        'interests.sports.soccer',
        'interests.sports.rockClimbing',
    ],
    [CategoriesMap[22]]: [
        'interests.business.businessTravel',
        'interests.travelTransport.travel',
    ],
    [CategoriesMap[24]]: [
        'interests.fashion.styleTrends',
        'interests.fashion.clothingAccessories',
        'interests.fashion.bodyArtCostume',
    ],
    [CategoriesMap[25]]: [
        'interests.foodDrink.cocktails',
        'interests.foodDrink.happyHour',
        'interests.foodDrink.coffee',
        'interests.foodDrink.juiceSmoothies',
    ],
    [CategoriesMap[26]]: [
        'interests.foodDrink.cocktails',
        'interests.arts.dance',
    ],
    [CategoriesMap[27]]: [
        'interests.sports.basketball',
        'interests.sports.baseball',
        'interests.sports.billiards',
        'interests.sports.bowling',
        'interests.sports.Climbing',
        'interests.sports.rockClimbing',
        'interests.sports.cycling',
        'interests.sports.football',
        'interests.sports.golf',
        'interests.sports.gymWorkouts',
        'interests.sports.gymnastics',
        'interests.sports.hockey',
        'interests.sports.running',
        'interests.sports.soccer',
        'interests.sports.tennis',
        'interests.sports.volleyball',
    ],
    [CategoriesMap[28]]: [
        'interests.sports.basketball',
        'interests.sports.baseball',
        'interests.sports.billiards',
        'interests.sports.bowling',
        'interests.sports.Climbing',
        'interests.sports.rockClimbing',
        'interests.sports.cycling',
        'interests.sports.football',
        'interests.sports.golf',
        'interests.sports.gymWorkouts',
        'interests.sports.gymnastics',
        'interests.sports.hockey',
        'interests.sports.running',
        'interests.sports.soccer',
        'interests.sports.tennis',
        'interests.sports.volleyball',
    ],
    [CategoriesMap[29]]: [
        'interests.arts.painting',
        'interests.arts.visualArts',
        'interests.arts.anime',
        'interests.arts.photography',
        'interests.arts.crafts',
        'interests.arts.drawing',
        'interests.arts.digitalArt',
        'interests.arts.textileArt',
        'interests.arts.dance',
        'interests.arts.instruments',
        'interests.arts.liveMusic',
        'interests.arts.singing',
        'interests.arts.comedy',
        'interests.arts.reading',
        'interests.business.businessTravel',
        'interests.business.collegeLife',
    ],
};

const MomentCategories = [
    CategoriesMap[1],
    CategoriesMap[3],
    CategoriesMap[7],
    CategoriesMap[4],
    CategoriesMap[6],
    CategoriesMap[8],
    CategoriesMap[22],
    CategoriesMap[28],
    CategoriesMap[26],
    CategoriesMap[19],
    CategoriesMap[13],
    CategoriesMap[24],
    CategoriesMap[23],
];

const SpaceCategories = [
    CategoriesMap[1],
    CategoriesMap[3],
    CategoriesMap[7],
    CategoriesMap[28],
    CategoriesMap[2],
    CategoriesMap[4],
    CategoriesMap[9],
    CategoriesMap[29],
    CategoriesMap[10],
    CategoriesMap[5],
    CategoriesMap[6],
    CategoriesMap[8],
];

const ThoughtCategories = MomentCategories;

const EventCategories = [
    ...MomentCategories,
    CategoriesMap[12],
];

export default {
    CategoriesMap,
    CategoryToInterestsMap,
    EventCategories,
    MomentCategories,
    SpaceCategories,
    ThoughtCategories,
};
