/* eslint-disable max-len */
const CategoriesMap = {
    1: 'categories.uncategorized',
    2: 'categories.storefront/shop',
    3: 'categories.restaurant/food',
    4: 'categories.bar/drinks',
    5: 'categories.marketplace/festival',
    6: 'categories.artwork/expression',
    7: 'categories.music/concerts',
    8: 'categories.nature/parks',
    9: 'categories.hotels/lodging',
    10: 'categories.event/space',
    11: 'categories.art',
    12: 'categories.gaming',
    13: 'categories.geocache',
    14: 'categories.menu',
    15: 'categories.music',
    16: 'categories.deals',
    17: 'categories.fitness',
    18: 'categories.storefront',
    19: 'categories.idea',
    20: 'categories.food',
    21: 'categories.nature',
    22: 'categories.travel',
    23: 'categories.warning',
    24: 'categories.seasonal',
    25: 'categories.drinks',
    26: 'categories.nightLife',
    27: 'categories.sports',
    28: 'categories.fitness/sports',
    29: 'categories.museum/academia',
};

const CategoryToInterestsMap = {
    2: [
        'interests.business.localBusiness',
    ],
    3: [
        'interests.foodDrink.dining',
        'interests.foodDrink.happyHour',
        'interests.foodDrink.desserts',
        'interests.foodDrink.foodTrucks',
        'interests.foodDrink.ramen',
        'interests.foodDrink.veganFood',
    ],
    4: [
        'interests.foodDrink.cocktails',
        'interests.foodDrink.happyHour',
        'interests.foodDrink.coffee',
        'interests.foodDrink.juiceSmoothies',
    ],
    5: [
        'interests.arts.visualArts',
        'interests.arts.liveMusic',
    ],
    6: [
        'interests.arts.painting',
        'interests.arts.visualArts',
        'interests.arts.anime',
        'interests.arts.photography',
        'interests.arts.crafts',
        'interests.arts.drawing',
        'interests.arts.digitalArt',
        'interests.arts.textileArt',
        'interests.arts.dance',
        'interests.arts.instruments',
        'interests.arts.liveMusic',
        'interests.arts.singing',
        'interests.arts.comedy',
        'interests.arts.reading',
    ],
    7: [
        'interests.arts.instruments',
        'interests.arts.liveMusic',
        'interests.arts.singing',
        'interests.foodDrink.happyHour',
    ],
    8: [
        'interests.sports.running',
        'interests.sports.cycling',
        'interests.sports.soccer',
        'interests.sports.Climbing',
    ],
    9: [
        'interests.business.businessTravel',
        'interests.travelTransport.travel',
    ],
    10: [
        'interests.business.localBusiness',
        'interests.arts.liveMusic',
        'interests.sports.baseball',
        'interests.sports.basketball',
        'interests.sports.football',
        'interests.sports.soccer',
        'interests.sports.hockey',
    ],
    11: [
        'interests.arts.painting',
        'interests.arts.visualArts',
        'interests.arts.anime',
        'interests.arts.photography',
        'interests.arts.crafts',
        'interests.arts.drawing',
        'interests.arts.digitalArt',
        'interests.arts.textileArt',
        'interests.arts.dance',
        'interests.arts.instruments',
        'interests.arts.liveMusic',
        'interests.arts.singing',
        'interests.arts.comedy',
        'interests.arts.reading',
    ],
    12: [
        'interests.games.videoGamesConsole',
        'interests.games.videoGamesComputer',
        'interests.games.tableTopGames',
        'interests.games.boardGames',
    ],
    13: [
        'interests.games.boardGames',
        'interests.travelTransport.travel',
    ],
    14: [
        'interests.foodDrink.dining',
        'interests.foodDrink.happyHour',
        'interests.foodDrink.cocktails',
        'interests.foodDrink.coffee',
        'interests.foodDrink.desserts',
        'interests.foodDrink.foodTrucks',
        'interests.foodDrink.juiceSmoothies',
        'interests.foodDrink.ramen',
        'interests.foodDrink.veganFood',
    ],
    15: [
        'interests.arts.instruments',
        'interests.arts.liveMusic',
        'interests.arts.singing',
        'interests.foodDrink.happyHour',
    ],
    16: [
        'interests.business.localBusiness',
        'interests.business.restaurant',
    ],
    17: [
        'interests.sports.gymWorkouts',
        'interests.sports.bowling',
        'interests.sports.Climbing',
        'interests.sports.rockClimbing',
        'interests.sports.cycling',
    ],
    18: [
        'interests.business.localBusiness',
        'interests.fashion.styleTrends',
        'interests.fashion.clothingAccessories',
    ],
    19: [
        'interests.arts.painting',
        'interests.arts.visualArts',
        'interests.arts.anime',
        'interests.arts.photography',
        'interests.arts.crafts',
        'interests.arts.drawing',
        'interests.arts.digitalArt',
        'interests.arts.textileArt',
        'interests.arts.dance',
        'interests.arts.instruments',
        'interests.arts.liveMusic',
        'interests.arts.singing',
        'interests.arts.comedy',
        'interests.arts.reading',
    ],
    20: [
        'interests.foodDrink.dining',
        'interests.foodDrink.happyHour',
        'interests.foodDrink.desserts',
        'interests.foodDrink.foodTrucks',
        'interests.foodDrink.ramen',
        'interests.foodDrink.veganFood',
    ],
    21: [
        'interests.sports.running',
        'interests.sports.cycling',
        'interests.sports.soccer',
        'interests.sports.rockClimbing',
    ],
    22: [
        'interests.business.businessTravel',
        'interests.travelTransport.travel',
    ],
    24: [
        'interests.fashion.styleTrends',
        'interests.fashion.clothingAccessories',
        'interests.fashion.bodyArtCostume',
    ],
    25: [
        'interests.foodDrink.cocktails',
        'interests.foodDrink.happyHour',
        'interests.foodDrink.coffee',
        'interests.foodDrink.juiceSmoothies',
    ],
    26: [
        'interests.foodDrink.cocktails',
        'interests.arts.dance',
    ],
    27: [
        'interests.sports.basketball',
        'interests.sports.baseball',
        'interests.sports.billiards',
        'interests.sports.bowling',
        'interests.sports.Climbing',
        'interests.sports.rockClimbing',
        'interests.sports.cycling',
        'interests.sports.football',
        'interests.sports.golf',
        'interests.sports.gymWorkouts',
        'interests.sports.gymnastics',
        'interests.sports.hockey',
        'interests.sports.running',
        'interests.sports.soccer',
        'interests.sports.tennis',
        'interests.sports.volleyball',
    ],
    28: [
        'interests.sports.basketball',
        'interests.sports.baseball',
        'interests.sports.billiards',
        'interests.sports.bowling',
        'interests.sports.Climbing',
        'interests.sports.rockClimbing',
        'interests.sports.cycling',
        'interests.sports.football',
        'interests.sports.golf',
        'interests.sports.gymWorkouts',
        'interests.sports.gymnastics',
        'interests.sports.hockey',
        'interests.sports.running',
        'interests.sports.soccer',
        'interests.sports.tennis',
        'interests.sports.volleyball',
    ],
    29: [
        'interests.arts.painting',
        'interests.arts.visualArts',
        'interests.arts.anime',
        'interests.arts.photography',
        'interests.arts.crafts',
        'interests.arts.drawing',
        'interests.arts.digitalArt',
        'interests.arts.textileArt',
        'interests.arts.dance',
        'interests.arts.instruments',
        'interests.arts.liveMusic',
        'interests.arts.singing',
        'interests.arts.comedy',
        'interests.arts.reading',
        'interests.business.businessTravel',
        'interests.business.collegeLife',
    ],
};

const MomentCategories = [
    CategoriesMap[1],
    CategoriesMap[20],
    CategoriesMap[15],
    CategoriesMap[25],
    CategoriesMap[11],
    CategoriesMap[21],
    CategoriesMap[22],
    CategoriesMap[17],
    CategoriesMap[26],
    CategoriesMap[19],
    CategoriesMap[13],
    CategoriesMap[24],
    CategoriesMap[23],
];

const SpaceCategories = [
    CategoriesMap[1],
    CategoriesMap[3],
    CategoriesMap[7],
    CategoriesMap[28],
    CategoriesMap[2],
    CategoriesMap[4],
    CategoriesMap[9],
    CategoriesMap[29],
    CategoriesMap[10],
    CategoriesMap[5],
    CategoriesMap[6],
    CategoriesMap[8],
];

const ThoughtCategories = MomentCategories;

const EventCategories = [
    ...MomentCategories,
    CategoriesMap[12],
];

export default {
    CategoriesMap,
    CategoryToInterestsMap,
    EventCategories,
    MomentCategories,
    SpaceCategories,
    ThoughtCategories,
};
