const locationConstants = {
    FALLBACK_CACHE_SEARCH_RADIUS_METERS: 50,
    AREA_PROXIMITY_METERS: 1000,
    AREA_PROXIMITY_EXPANDED_METERS: 100000, // ~62 miles
    MAX_AREA_ACTIVATE_COUNT: 10,
    MIN_TIME_BETWEEN_PUSH_NOTIFICATIONS_MS: 1000 * 60 * 3, // 3 minutes
    MIN_RADIUS_OF_AWARENESS: 10,
    MAX_RADIUS_OF_AWARENESS: 1000,
    MIN_RADIUS_OF_INFLUENCE: 10,
    MAX_RADIUS_OF_INFLUENCE: 1000,
};

export default locationConstants;
