const locationConstants = {
    FALLBACK_CACHE_SEARCH_RADIUS_METERS: 50,
    MOMENT_PROXIMITY_METERS: 1000,
    MOMENT_PROXIMITY_EXPANDED_METERS: 2000,
    MAX_MOMENT_ACTIVATE_COUNT: 10,
    MIN_TIME_BETWEEN_PUSH_NOTIFICATIONS_MS: 1000 * 60 * 3, // 3 minutes
};

export default locationConstants;
