// IMPORTANT: Developers should update version after making any changes to these configs. An achievement key/id should never be changed
// NOTE: title and description should be translated by the consumer of this config
// SCOPE: Awarded for break_bad habit goal type — abstinence streak ladder. Tier 1 (day 1) is included
// because the first 24 hours is its own milestone for breaking habits.

const cleanBreakAchievements = {
    cleanBreak_1_1: {
        title: 'First Day Free',
        description: 'Complete 1 day without breaking a habit',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 1,
        xp: 10,
        pointReward: 0.25,
        mediaId: 'first-day-free',
        tier: '1_1',
        version: 1,
    },
    cleanBreak_1_1_1: {
        title: 'Three Strong',
        description: 'Reach a 3-day clean streak',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.cleanBreak_1_1,
        countToComplete: 3,
        xp: 20,
        pointReward: 0.50,
        mediaId: 'three-strong',
        tier: '1_1',
        version: 1,
    },
    cleanBreak_1_1_2: {
        title: 'One Week Clean',
        description: 'Reach a 7-day clean streak',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.cleanBreak_1_1_1,
        countToComplete: 7,
        xp: 30,
        pointReward: 1.00,
        mediaId: 'one-week-clean',
        tier: '1_1',
        version: 1,
    },
    cleanBreak_1_1_3: {
        title: 'Two Weeks Clear',
        description: 'Reach a 14-day clean streak',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.cleanBreak_1_1_2,
        countToComplete: 14,
        xp: 50,
        pointReward: 2.00,
        mediaId: 'two-weeks-clear',
        tier: '1_1',
        version: 1,
    },
    cleanBreak_1_1_4: {
        title: 'Thirty Days Reborn',
        description: 'Reach a 30-day clean streak',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.cleanBreak_1_1_3,
        countToComplete: 30,
        xp: 100,
        pointReward: 4.00,
        mediaId: 'thirty-days-reborn',
        tier: '1_1',
        version: 1,
    },
    cleanBreak_1_1_5: {
        title: 'Sixty Day Stride',
        description: 'Reach a 60-day clean streak',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.cleanBreak_1_1_4,
        countToComplete: 60,
        xp: 150,
        pointReward: 6.00,
        mediaId: 'sixty-day-stride',
        tier: '1_1',
        version: 1,
    },
    cleanBreak_1_1_6: {
        title: 'Ninety Day Reset',
        description: 'Reach a 90-day clean streak',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.cleanBreak_1_1_5,
        countToComplete: 90,
        xp: 200,
        pointReward: 8.00,
        mediaId: 'ninety-day-reset',
        tier: '1_1',
        version: 1,
    },
    cleanBreak_1_1_7: {
        title: 'Half Year Free',
        description: 'Reach a 180-day clean streak',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.cleanBreak_1_1_6,
        countToComplete: 180,
        xp: 300,
        pointReward: 15.00,
        mediaId: 'half-year-free',
        tier: '1_1',
        version: 1,
    },
    cleanBreak_1_1_8: {
        title: 'A Year Reborn',
        description: 'Reach a 365-day clean streak',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.cleanBreak_1_1_7,
        countToComplete: 365,
        xp: 750,
        pointReward: 35.00,
        mediaId: 'a-year-reborn',
        tier: '1_1',
        version: 1,
    },
};

export default cleanBreakAchievements;
