// IMPORTANT: Developers should update version after making any changes to these configs. An achievement key/id should never be changed
// NOTE: title and description should be translated by the consumer of this config
// using translation keys (ex. explorer_1_1.title, explorer_1_1.description)

const explorerAchievements = {
    explorer_1_1: {
        title: 'Explore',
        description: 'Activate 10 Moments',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 10,
        xp: 10,
        pointReward: 1.00,
        mediaId: 'explore',
        tier: '1_1',
        version: 1,
    },
    explorer_1_1_1: {
        title: 'Discover',
        description: 'Activate 100 Moments',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.explorer_1_1,
        countToComplete: 100,
        xp: 20,
        pointReward: 2.00,
        mediaId: 'discover',
        tier: '1_1',
        version: 1,
    },
    explorer_1_1_2: {
        title: 'Gather',
        description: 'Activate 500 Moments',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.explorer_1_1_1,
        countToComplete: 500,
        xp: 25,
        pointReward: 1.00,
        mediaId: 'gather',
        tier: '1_1',
        version: 1,
    },
    explorer_1_1_3: {
        title: 'Branch Out',
        description: 'Activate 1,000 Moments',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.explorer_1_1_2,
        countToComplete: 1000,
        xp: 45,
        pointReward: 1.00,
        mediaId: 'branch-out',
        tier: '1_1',
        version: 1,
    },
    explorer_1_1_4: {
        title: 'New Perspectives',
        description: 'Activate 2,500 Moments',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.explorer_1_1_3,
        countToComplete: 2500,
        xp: 90,
        pointReward: 2.00,
        mediaId: 'new-perspectives',
        tier: '1_1',
        version: 1,
    },
    explorer_1_1_5: {
        title: 'The Great Expansion',
        description: 'Activate 5,000 Moments',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.explorer_1_1_4,
        countToComplete: 5000,
        xp: 100,
        pointReward: 2.00,
        mediaId: 'the-great-expansion',
        tier: '1_1',
        version: 1,
    },
    explorer_1_1_6: {
        title: 'Explore the World',
        description: 'Activate 10,000 Moments',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.explorer_1_1_5,
        countToComplete: 10000,
        xp: 100,
        pointReward: 5.00,
        mediaId: 'explore-the-world',
        tier: '1_1',
        version: 1,
    },
    explorer_1_2: {
        title: 'New Discoveries',
        description: 'Discover 5 Moment Categories',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 5,
        xp: 20,
        pointReward: 1.00,
        mediaId: 'new-discoveries',
        tier: '1_2',
        version: 1,
    },
    explorer_1_2_1: {
        title: 'Diversity of Mind',
        description: 'Discover 5 Moment Categories',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.explorer_1_2,
        countToComplete: 5,
        xp: 25,
        pointReward: 1.00,
        mediaId: 'diversity-of-mind',
        tier: '1_2',
        version: 1,
    },
    explorer_1_3: {
        title: 'Network',
        description: 'Activate 5 Spaces',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 5,
        xp: 10,
        pointReward: 1.00,
        mediaId: 'network',
        tier: '1_3',
        version: 1,
    },
    explorer_1_3_1: {
        title: 'Network Developer',
        description: 'Activate 15 Spaces',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.explorer_1_3,
        countToComplete: 15,
        xp: 20,
        pointReward: 2.00,
        mediaId: 'network-developer',
        tier: '1_3',
        version: 1,
    },
    explorer_1_3_2: {
        title: 'Network Expansion',
        description: 'Activate 50 Spaces',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.explorer_1_3_1,
        countToComplete: 50,
        xp: 50,
        pointReward: 2.00,
        mediaId: 'network-expansion',
        tier: '1_3',
        version: 1,
    },
    explorer_1_3_3: {
        title: 'Networking Leader',
        description: 'Activate 100 Spaces',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.explorer_1_3_2,
        countToComplete: 100,
        xp: 100,
        pointReward: 3.00,
        mediaId: 'networking-leader',
        tier: '1_3',
        version: 1,
    },
    explorer_1_3_4: {
        title: 'Space Wizard',
        description: 'Activate 500 Spaces',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.explorer_1_3_3,
        countToComplete: 500,
        xp: 250,
        pointReward: 5.00,
        mediaId: 'space-wizard',
        tier: '1_3',
        version: 1,
    },
    explorer_1_4: {
        title: 'Eventful',
        description: 'Activate 1 Event',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 1,
        xp: 10,
        pointReward: 1.00,
        mediaId: 'eventful',
        tier: '1_4',
        version: 1,
    },
    explorer_1_4_1: {
        title: 'Face in the Crowd',
        description: 'Activate 3 Events',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.explorer_1_4,
        countToComplete: 3,
        xp: 50,
        pointReward: 2.00,
        mediaId: 'face-in-the-crowd',
        tier: '1_4',
        version: 1,
    },
    explorer_1_4_2: {
        title: 'Have we met?',
        description: 'Activate 10 Events',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.explorer_1_4_1,
        countToComplete: 10,
        xp: 75,
        pointReward: 3.00,
        mediaId: 'have-we-met',
        tier: '1_4',
        version: 1,
    },
    explorer_1_4_3: {
        title: 'Right Place, Right Time',
        description: 'Activate 100 Events',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.explorer_1_4_2,
        countToComplete: 100,
        xp: 100,
        pointReward: 5.00,
        mediaId: 'right-place-right-time',
        tier: '1_4',
        version: 1,
    },
    explorer_1_4_4: {
        title: 'See You Therr',
        description: 'Activate 250 Events',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.explorer_1_4_3,
        countToComplete: 250,
        xp: 250,
        pointReward: 5.00,
        mediaId: 'see-you-therr',
        tier: '1_4',
        version: 1,
    },
};

export default explorerAchievements;
