// IMPORTANT: Developers should update version after making any changes to these configs. An achievement key/id should never be changed
// NOTE: title and description should be translated by the consumer of this config
// using translation keys (ex. habitBuilder_1_1.title, habitBuilder_1_1.description)
// SCOPE: Awarded for build_good and maintenance habit goal types — daily streak ladder.

const habitBuilderAchievements = {
    habitBuilder_1_1: {
        title: 'First Steps',
        description: 'Reach a 3-day streak on a habit',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 3,
        xp: 10,
        pointReward: 0.25,
        mediaId: 'first-steps',
        tier: '1_1',
        version: 1,
    },
    habitBuilder_1_1_1: {
        title: 'One Week Strong',
        description: 'Reach a 7-day streak on a habit',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.habitBuilder_1_1,
        countToComplete: 7,
        xp: 20,
        pointReward: 0.50,
        mediaId: 'one-week-strong',
        tier: '1_1',
        version: 1,
    },
    habitBuilder_1_1_2: {
        title: 'Two Week Wonder',
        description: 'Reach a 14-day streak on a habit',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.habitBuilder_1_1_1,
        countToComplete: 14,
        xp: 30,
        pointReward: 1.00,
        mediaId: 'two-week-wonder',
        tier: '1_1',
        version: 1,
    },
    habitBuilder_1_1_3: {
        title: 'Habit Formed',
        description: 'Reach a 30-day streak on a habit',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.habitBuilder_1_1_2,
        countToComplete: 30,
        xp: 60,
        pointReward: 2.00,
        mediaId: 'habit-formed',
        tier: '1_1',
        version: 1,
    },
    habitBuilder_1_1_4: {
        title: 'Two Months In',
        description: 'Reach a 60-day streak on a habit',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.habitBuilder_1_1_3,
        countToComplete: 60,
        xp: 90,
        pointReward: 3.00,
        mediaId: 'two-months-in',
        tier: '1_1',
        version: 1,
    },
    habitBuilder_1_1_5: {
        title: 'Quarter Master',
        description: 'Reach a 90-day streak on a habit',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.habitBuilder_1_1_4,
        countToComplete: 90,
        xp: 120,
        pointReward: 5.00,
        mediaId: 'quarter-master',
        tier: '1_1',
        version: 1,
    },
    habitBuilder_1_1_6: {
        title: 'Half Year Hero',
        description: 'Reach a 180-day streak on a habit',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.habitBuilder_1_1_5,
        countToComplete: 180,
        xp: 200,
        pointReward: 10.00,
        mediaId: 'half-year-hero',
        tier: '1_1',
        version: 1,
    },
    habitBuilder_1_1_7: {
        title: 'Habit Legend',
        description: 'Reach a 365-day streak on a habit',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.habitBuilder_1_1_6,
        countToComplete: 365,
        xp: 500,
        pointReward: 25.00,
        mediaId: 'habit-legend',
        tier: '1_1',
        version: 1,
    },
};

export default habitBuilderAchievements;
