// IMPORTANT: Developers should update version after making any changes to these configs. An achievement key/id should never be changed
// NOTE: title and description should be translated by the consumer of this config
// using translation keys (ex. explorer_1_1.title, explorer_1_1.description)

const influencerAchievements = {
    influencer_1_1: {
        title: 'Likable',
        description: 'Get 5 likes',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 5,
        xp: 10,
        pointReward: 1.00,
        mediaId: 'likable',
        tier: '1_1',
        version: 1,
    },
    influencer_1_1_1: {
        title: 'Very Likable',
        description: 'Get 20 likes',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.influencer_1_1,
        countToComplete: 20,
        xp: 10,
        pointReward: 1.00,
        mediaId: 'very-likable',
        tier: '1_1',
        version: 1,
    },
    influencer_1_1_2: {
        title: 'Intriguing',
        description: 'Get 50 likes',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.influencer_1_1_1,
        countToComplete: 50,
        xp: 20,
        pointReward: 2.00,
        mediaId: 'intriguing',
        tier: '1_1',
        version: 1,
    },
    influencer_1_1_3: {
        title: 'Too Cool',
        description: 'Get 100 likes',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.influencer_1_1_2,
        countToComplete: 100,
        xp: 50,
        pointReward: 2.00,
        mediaId: 'too-cool',
        tier: '1_1',
        version: 1,
    },
    influencer_1_1_4: {
        title: 'So Very Likable',
        description: 'Get 500 likes',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.influencer_1_1_3,
        countToComplete: 500,
        xp: 100,
        pointReward: 2.00,
        mediaId: 'so-very-likable',
        tier: '1_1',
        version: 1,
    },
    influencer_1_1_5: {
        title: 'Regally Liked',
        description: 'Get 2,500 likes',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.influencer_1_1_4,
        countToComplete: 2500,
        xp: 150,
        pointReward: 2.00,
        mediaId: 'regally-liked',
        tier: '1_1',
        version: 1,
    },
    influencer_1_2: {
        title: 'Super Liked',
        description: 'Get 1 superlike on a post',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 1,
        xp: 10,
        pointReward: 1.00,
        mediaId: 'super-liked',
        tier: '1_2',
        version: 1,
    },
    influencer_1_2_1: {
        title: 'Super Creative',
        description: 'Get 5 superlike',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.influencer_1_2,
        countToComplete: 5,
        xp: 50,
        pointReward: 2.00,
        mediaId: 'super-creative',
        tier: '1_2',
        version: 1,
    },
    influencer_1_2_2: {
        title: 'Super Influencer',
        description: 'Get 15 superlike',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.influencer_1_2_1,
        countToComplete: 15,
        xp: 100,
        pointReward: 3.00,
        mediaId: 'super-influencer',
        tier: '1_2',
        version: 1,
    },
    influencer_1_2_3: {
        title: 'Superhuman',
        description: 'Get 50 superlike',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.influencer_1_2_2,
        countToComplete: 50,
        xp: 100,
        pointReward: 5.00,
        mediaId: 'superhuman',
        tier: '1_2',
        version: 1,
    },
    influencer_1_3: {
        title: 'Creator',
        description: 'Create 1 moment',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 1,
        xp: 10,
        pointReward: 0.50,
        mediaId: 'creator',
        tier: '1_3',
        version: 1,
    },
    influencer_1_3_1: {
        title: 'Content Creator',
        description: 'Create 5 moments',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.influencer_1_3,
        countToComplete: 5,
        xp: 25,
        pointReward: 1.00,
        mediaId: 'content-creator',
        tier: '1_3',
        version: 1,
    },
    influencer_1_3_2: {
        title: 'In the Moment',
        description: 'Create 10 moments',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.influencer_1_3_1,
        countToComplete: 10,
        xp: 25,
        pointReward: 1.00,
        mediaId: 'in-the-moment',
        tier: '1_3',
        version: 1,
    },
    influencer_1_3_3: {
        title: 'Expressive',
        description: 'Create 50 moments',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.influencer_1_3_2,
        countToComplete: 50,
        xp: 30,
        pointReward: 1.00,
        mediaId: 'expressive',
        tier: '1_3',
        version: 1,
    },
    influencer_1_3_4: {
        title: 'Magic Maker',
        description: 'Create 100 moments',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.influencer_1_3_3,
        countToComplete: 100,
        xp: 35,
        pointReward: 5.00,
        mediaId: 'magic-maker',
        tier: '1_3',
        version: 1,
    },
    influencer_1_3_5: {
        title: 'Professional Creator',
        description: 'Create 250 moments',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.influencer_1_3_4,
        countToComplete: 250,
        xp: 50,
        pointReward: 5.00,
        mediaId: 'professional-creator',
        tier: '1_3',
        version: 1,
    },
    influencer_1_3_6: {
        title: 'Sage Creator',
        description: 'Create 500 moments',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.influencer_1_3_5,
        countToComplete: 500,
        xp: 75,
        pointReward: 5.00,
        mediaId: 'sage-creator',
        tier: '1_3',
        version: 1,
    },
    influencer_1_3_7: {
        title: 'Unstoppable Creativity',
        description: 'Create 1,000 moments',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.influencer_1_3_6,
        countToComplete: 1000,
        xp: 150,
        pointReward: 5.00,
        mediaId: 'unstoppable-creativity',
        tier: '1_3',
        version: 1,
    },
};

export default influencerAchievements;
