// IMPORTANT: Developers should update version after making any changes to these configs. An achievement key/id should never be changed
// NOTE: title and description should be translated by the consumer of this config
// using translation keys (ex. explorer_1_1.title, explorer_1_1.description)

const socialiteAchievements = {
    socialite_1_1: {
        title: 'Friendly',
        description: 'Invite 3 friends',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 3,
        xp: 10,
        pointReward: 1.00,
        mediaId: 'friendly',
        tier: '1_1',
        version: 1,
    },
    socialite_1_1_1: {
        title: 'Be Social',
        description: 'Invite 10 friends',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 10,
        xp: 15,
        pointReward: 2.00,
        mediaId: 'be-social',
        tier: '1_1',
        version: 1,
    },
    socialite_1_1_2: {
        title: 'Initiator',
        description: 'Invite 25 friends',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 25,
        xp: 20,
        pointReward: 2.00,
        mediaId: 'initiator',
        tier: '1_1',
        version: 1,
    },
    socialite_1_1_3: {
        title: 'Building a Network',
        description: 'Invite 50 friends',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 50,
        xp: 50,
        pointReward: 2.00,
        mediaId: '',
        tier: '1_1',
        version: 1,
    },
    socialite_1_1_4: {
        title: 'Extend Your Borders',
        description: 'Invite 100 friends',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 100,
        xp: 75,
        pointReward: 3.00,
        mediaId: 'extend-your-borders',
        tier: '1_1',
        version: 1,
    },
    socialite_1_1_5: {
        title: 'All In',
        description: 'Invite 500 friends',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 500,
        xp: 150,
        pointReward: 5.00,
        mediaId: 'all-in',
        tier: '1_1',
        version: 1,
    },
    socialite_1_1_6: {
        title: 'Tell the World',
        description: 'Invite 1000 friends',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 1000,
        xp: 200,
        pointReward: 10.00,
        mediaId: 'tell-the-world',
        tier: '1_1',
        version: 1,
    },
    socialite_1_2: {
        title: 'Break the Ice',
        description: 'Make 1 friendships/connections',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 1,
        xp: 10,
        pointReward: 1.00,
        mediaId: 'break-the-ice',
        tier: '1_2',
        version: 1,
    },
    socialite_1_2_1: {
        title: 'New Friends',
        description: 'Make 3 friendships/connections',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 3,
        xp: 10,
        pointReward: 1.00,
        mediaId: 'new-friends',
        tier: '1_2',
        version: 1,
    },
    socialite_1_2_2: {
        title: 'Social Circle',
        description: 'Make 10 friendships/connections',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 10,
        xp: 10,
        pointReward: 1.00,
        mediaId: 'social-circle',
        tier: '1_2',
        version: 1,
    },
    socialite_1_2_3: {
        title: 'Getting Popular',
        description: 'Make 50 friendships/connections',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 50,
        xp: 10,
        pointReward: 2.00,
        mediaId: 'getting-popular',
        tier: '1_2',
        version: 1,
    },
    socialite_1_2_4: {
        title: 'Strength In Numbers',
        description: 'Make 100 friendships/connections',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 100,
        xp: 10,
        pointReward: 2.00,
        mediaId: 'strength-in-numbers',
        tier: '1_2',
        version: 1,
    },
    socialite_1_2_5: {
        title: 'Diversify',
        description: 'Make 250 friendships/connections',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 250,
        xp: 10,
        pointReward: 3.00,
        mediaId: 'diversify',
        tier: '1_2',
        version: 1,
    },
    socialite_1_2_6: {
        title: 'Social Butterfly',
        description: 'Make 1000 friendships/connections',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 1000,
        xp: 10,
        pointReward: 5.00,
        mediaId: 'social-butterfly',
        tier: '1_2',
        version: 1,
    },
    socialite_1_2_7: {
        title: 'Almost Famous',
        description: 'Make 5000 friendships/connections',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 5000,
        xp: 10,
        pointReward: 10.00,
        mediaId: 'almost-famous',
        tier: '1_2',
        version: 1,
    },
    socialite_1_2_8: {
        title: 'Definitely Famous',
        description: 'Make 10000 friendships/connections',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 10000,
        xp: 10,
        pointReward: 15.00,
        mediaId: 'definitely-famous',
        tier: '1_2',
        version: 1,
    },
};

export default socialiteAchievements;
