// IMPORTANT: Developers should update version after making any changes to these configs. An achievement key/id should never be changed
// NOTE: title and description should be translated by the consumer of this config
// SCOPE: Awarded for savings_goal habit goal type. Tier 1 = no-spend day streaks. Tier 2 = savings pacts completed.

const treasureBuilderAchievements = {
    // Tier 1 — no-spend day streaks
    treasureBuilder_1_1: {
        title: 'Penny Saved',
        description: 'Reach a 7-day no-spend streak',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 7,
        xp: 20,
        pointReward: 0.50,
        mediaId: 'penny-saved',
        tier: '1_1',
        version: 1,
    },
    treasureBuilder_1_1_1: {
        title: 'Frugal Fortnight',
        description: 'Reach a 14-day no-spend streak',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.treasureBuilder_1_1,
        countToComplete: 14,
        xp: 40,
        pointReward: 1.50,
        mediaId: 'frugal-fortnight',
        tier: '1_1',
        version: 1,
    },
    treasureBuilder_1_1_2: {
        title: 'Coin Collector',
        description: 'Reach a 30-day no-spend streak',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.treasureBuilder_1_1_1,
        countToComplete: 30,
        xp: 75,
        pointReward: 3.00,
        mediaId: 'coin-collector',
        tier: '1_1',
        version: 1,
    },
    treasureBuilder_1_1_3: {
        title: 'Vault Keeper',
        description: 'Reach a 60-day no-spend streak',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.treasureBuilder_1_1_2,
        countToComplete: 60,
        xp: 150,
        pointReward: 5.00,
        mediaId: 'vault-keeper',
        tier: '1_1',
        version: 1,
    },
    treasureBuilder_1_1_4: {
        title: 'Treasure Hunter',
        description: 'Reach a 100-day no-spend streak',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.treasureBuilder_1_1_3,
        countToComplete: 100,
        xp: 250,
        pointReward: 10.00,
        mediaId: 'treasure-hunter',
        tier: '1_1',
        version: 1,
    },

    // Tier 2 — savings pacts completed
    treasureBuilder_1_2: {
        title: 'First Goal Reached',
        description: 'Complete 1 savings pact',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => true,
        countToComplete: 1,
        xp: 25,
        pointReward: 1.00,
        mediaId: 'first-goal-reached',
        tier: '1_2',
        version: 1,
    },
    treasureBuilder_1_2_1: {
        title: 'Goal Setter',
        description: 'Complete 3 savings pacts',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.treasureBuilder_1_2,
        countToComplete: 3,
        xp: 75,
        pointReward: 3.00,
        mediaId: 'goal-setter',
        tier: '1_2',
        version: 1,
    },
    treasureBuilder_1_2_2: {
        title: 'Wealth Builder',
        description: 'Complete 10 savings pacts',
        bonusAbilityId: '',
        prerequisite: (userAchievements: { [key: string]: any }) => !!userAchievements.treasureBuilder_1_2_1,
        countToComplete: 10,
        xp: 200,
        pointReward: 8.00,
        mediaId: 'wealth-builder',
        tier: '1_2',
        version: 1,
    },
};

export default treasureBuilderAchievements;
